---
title: "Untitled"
author: "baf44"
date: "1/3/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import data}
#data <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/untouchedRaw/GNG_Raw/GNG_Zoo_Raw_103-1.txt")

data <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/untouchedRaw/GNG_Raw/GNG_Zoo_Raw_072-1.txt")

#select block
df <- data[ which(data$Procedure.Block.=="Block3"), ]
```

```{r summary, echo=FALSE}

### Gen new variables ###
#trial_resp: indicate if response made during trial (stim or response screen)
df$trial_resp <- ifelse(df$Respond.RESP == "{SPACE}", "{SPACE}", 
                        ifelse( df$Stim.RESP == "{SPACE}", "{SPACE}", ""))

#trial_rt: indicate reaction time from onset of stim screen (add 750 ms to respond_rt if response occured during response screen)
df$trial_rt <- ifelse(df$Respond.RT > 0, df$Respond.RT + 750, 
                        ifelse( df$Stim.RT > 0, df$Stim.RT, ""))

#trial_acc: set accuracy equal to 1 when ca = trial_resp
df$trial_acc <- ifelse(df$trial_resp == df$CA, 1, 0)

### Summary variables ###
# Create 2 dataframes, one with Go trials and one with No Go trials
Go_data <- df[ which(df$compatibility=='Go'), ]
NoGo_data <- df[ which(df$compatibility=='NoGo'), ]

# count trials
nGo = nrow(Go_data)
nNoGo = nrow(NoGo_data)

# Accuracy
nAcc = sum(df$trial_acc)
pAcc = nAcc/nrow(df)

# Go Hits/Misses
nGo_Hit = sum(Go_data$trial_acc)
pGo_Hit = nGo_Hit/nrow(Go_data)

nGo_Miss = sum(Go_data$trial_acc == 0)
pGo_Miss = nGo_Miss/nrow(Go_data)

#NoGo Commissions (False Alarms) and Correct no responses  
nNoGo_Corr = sum(NoGo_data$trial_acc)
pNoGo_Corr = nNoGo_Corr/nrow(NoGo_data)

nNoGo_FA = sum(NoGo_data$trial_acc == 0)
pNoGo_FA = nNoGo_FA/nrow(NoGo_data)

# Mean and median RT
df$trial_rt <- as.numeric(df$trial_rt)
RTmeanGo_Hit = mean(df$trial_rt[df$trial_acc == 1], na.rm = TRUE)
RTmedGo_Hit = median(df$trial_rt[df$trial_acc == 1], na.rm = TRUE)

RTmeanNoGo_FA = mean(df$trial_rt[df$trial_acc == 0], na.rm = TRUE)
RTmedNoGo_FA = median(df$trial_rt[df$trial_acc == 0], na.rm = TRUE)

## SDT metrics
#z-score for hit and false alarm rates
z_Hit <- qnorm(pGo_Hit) 
z_FA <- qnorm(pNoGo_FA)

#do Macmillian adjustments for extreme values: if hit rate = 1, new hit
#rate = (nGo - 0.5)/nGo; if false alarm rate = 0, new false alarm rate
#= 0.5/nNoGo. If no extreme value, then just save standard calculation
#for z in that place

pHit_mm <- ifelse(pGo_Hit == 1, (nGo - 0.5)/nGo, pGo_Hit)
z_Hit_mm <- qnorm(pHit_mm)

pFA_mm <- ifelse(pNoGo_FA == 0, 0.5/nNoGo, pNoGo_FA)
z_FA_mm <- qnorm(pFA_mm)

#do loglinear adjustments: add 0.5 to NUMBER of hits and FA and add 1
#to number of Go and NoGo trials. Then caluculate z off of new hit and
#FA rates
nHit_ll = nGo_Hit + 0.5
nGo_ll = nGo + 1
nFA_ll = nNoGo_FA + 0.5
nNoGo_ll = nNoGo + 1
pHit_ll = nHit_ll/nGo_ll
pFA_ll = nFA_ll/nNoGo_ll
z_Hit_ll = qnorm(pHit_ll)
z_FA_ll = qnorm(pFA_ll)

## Formulas below have been verified by bari fuchs against:
## Calculation of signal detection theory measures (STANISLAW TODOROV 1999)

#calculate sensory sensitivity d'
d_prime_mm = z_Hit_mm - z_FA_mm
d_prime_ll = z_Hit_ll - z_FA_ll

#calculate nonparametric sensory sensitivity A':
#0.5+[sign(H-FA)*((H-FA)^2 + |H-FA|)/(4*max(H, FA) - 4*H*FA))
A_prime_mm = 0.5 + (sign(pHit_mm-pFA_mm)*((((pHit_mm-pFA_mm)**2+abs(pHit_mm - pFA_mm)))/(4*max(pHit_mm, pFA_mm) - 4*pHit_mm*pFA_mm)))
A_prime_ll = 0.5 + sign(pHit_ll-pFA_ll)*(((pHit_ll-pFA_ll)**2+abs(pHit_ll - pFA_ll))/(4*max(pHit_ll, pFA_ll) - 4*pHit_ll*pFA_ll))

#calculate c (criterion)
c_mm = (qnorm(pHit_mm) + qnorm(pFA_mm))/2
c_ll = (qnorm(pHit_ll) + qnorm(pFA_ll))/2

#calculate Grier's Beta--beta", a nonparametric response bias
Grier_beta_mm = sign(pHit_mm-pFA_mm)*((pHit_mm*(1-pHit_mm)-pFA_mm*(1-pFA_mm))/(pHit_mm*(1-pHit_mm)+pFA_mm*(1-pFA_mm)))
Grier_beta_ll = sign(pHit_ll-pFA_ll)*((pHit_ll*(1-pHit_ll)-pFA_ll*(1-pFA_ll))/(pHit_ll*(1-pHit_ll)+pFA_ll*(1-pFA_ll)))

```
