---
title: "summarydata_verification"
author: "baf44"
date: "9/14/2021"
output: html_document
---

Code to verify summarydata output

# SST
```{r import SST data, include=FALSE}
sst_007 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-007/ses-1/beh/sub-007_ses-1_task-sst_events.tsv")

sst_036 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-036/ses-1/beh/sub-036_ses-1_task-sst_events.tsv")

sst_017 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-017/ses-1/beh/sub-017_ses-1_task-sst_events.tsv")

sst_021 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-021/ses-1/beh/sub-021_ses-1_task-sst_events.tsv")

sst_056 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-056/ses-1/beh/sub-056_ses-1_task-sst_events.tsv")

```

```{r select SST dataset to test, include=FALSE}
df <- sst_036

# isolate hED trials
df <- df[ which(df$block_cond=='hED_lPort' | df$block_cond=='hED_sPort' ), ]

# isolate lED trials
df <- df[ which(df$block_cond=='lED_lPort' | df$block_cond=='lED_sPort' ), ]

# isolate small portion
df <- df[ which(df$block_cond=='hED_sPort' | df$block_cond=='lED_sPort' ), ]

# isolate large portion
df <- df[ which(df$block_cond=='hED_lPort' | df$block_cond=='lED_lPort' ), ]

# isolate large portion hED
df <- df[ which(df$block_cond=='hED_lPort' ), ]


targettrials_df <- df[ which(df$stop_signal=='0'), ] #df with no stop trials
stoptrials_df <- df[ which(df$stop_signal=='1'), ] #df with stop trials
```

```{r SST cond wide vars}

# number of stop trials (stop_signal = 1)
all_n_stop_trials <- nrow(stoptrials_df)

# number of go trials (stop_signal = 0)
all_n_go_trials <- nrow(targettrials_df)

# average reaction time across all go trials where a response was made
all_go_rt <- mean(targettrials_df$rt_1[targettrials_df$rt_1>0])

#number of correct responses (left/right) across all go trials
all_n_go_cor <- length(which(targettrials_df$correct==4))

#average reaction time across all correct go trials
all_go_cor_rt <- mean(targettrials_df$rt_1[targettrials_df$correct==4 & targettrials_df$rt_1>0])

#number of errors (left/right) across all go trials
all_n_go_error <- length(which(targettrials_df$correct==2))

# average go reaction time on across all go trials with error
all_go_error_rt <- mean(targettrials_df$rt_1[targettrials_df$correct==2 & targettrials_df$rt_1>0])

# number of missed go responses across all go trials
all_n_go_miss <- length(which(targettrials_df$correct==1))

#probability of responding on stop trials across all trials - p(resp|stop signal)
all_stop_prob_resp <- length(which(stoptrials_df$correct==3))/all_n_stop_trials

#average reaction time on unsuccessful stop trials across all trials
all_us_rt <- mean(stoptrials_df$rt_1[stoptrials_df$correct==3 & stoptrials_df$rt_1>0])

#average stop-signal delay across all stop trials"
all_ssd <- mean(stoptrials_df$true_ssd)

# stop-signal reaction time calculated using the mean method (mean rt to go trials - mean ssd) across all trials. Only calculated if racehorse assumption is met
all_ssrt_mean <- mean(targettrials_df$rt_1[targettrials_df$correct!=1]) - all_ssd

# stop-signal reaction time calculated using the integration method (nth rt - mean ssd) across all trials. Only calcualted if racehorse assumption is met
#all_ssrt_int

values <- list(all_n_stop_trials, all_n_go_trials, all_go_rt, all_n_go_cor, all_go_cor_rt, all_n_go_error, all_go_error_rt, all_n_go_miss, all_stop_prob_resp, all_us_rt, all_ssd, all_ssrt_mean)

print(values)
```


# GNG
```{r import GNG data, include=FALSE}
gng_007 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-007/ses-1/beh/sub-007_ses-1_task-gng_events.tsv")

gng_011 <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/raw_data/sub-011/ses-1/beh/sub-011_ses-1_task-gng_events.tsv")

gng_summary <- read.delim("~/OneDrive - The Pennsylvania State University/b-childfoodlab_Shared/Active_Studies/RO1_Brain_Mechanisms_IRB_5357/Participant_Data/BIDSdat/derivatives/preprocessed/beh/task-gng_summary.tsv")

```

```{r select GNG dataset to test, include=FALSE}
df <- gng_011

# isolate block 1
df <- df[ which(df$block==1 ), ]


# trial_resp = "{SPACE}" if response was made during stim or resp screens
df[df$stim_resp == "{SPACE}" | df$respond_resp == "{SPACE}", "trial_resp"] <- '{SPACE}'

# trial_rt
df$trial_rt<-ifelse(df$respond_resp == "{SPACE}",df$respond_rt + 750, df$stim_rt)

#visually confirm
df[, c("respond_rt", "stim_rt", "trial_rt")]

#trial_acc
df$trial_resp[is.na(df$trial_resp)] <- "" 
df$trial_acc <- ifelse(df$ca == df$trial_resp, 1, 0)

# Go dataframe
Go_data <- df[which(df$compatibility == 'Go'), ]
# No Go dataframe
NoGo_data <- df[which(df$compatibility == 'NoGo'), ]

#trial counts
nGo = nrow(Go_data)
nNoGo = nrow(NoGo_data)

#Accuracy
nAcc <- length(which(df$trial_acc==1))
pAcc <- nAcc/nrow(df)

#number of Go hits / misses
nGo_Hit = length(which(Go_data$trial_acc==1))
pGo_Hit = nGo_Hit/nrow(Go_data)
nGo_Miss = length(which(Go_data$trial_acc==0))
pGo_Miss = nGo_Miss/nrow(Go_data)

#number of NoGo hits / misses
nNoGo_corr = length(which(NoGo_data$trial_acc==1))
pNoGo_corr = nNoGo_corr/nrow(NoGo_data)

nNoGo_FA = length(which(NoGo_data$trial_acc==0))
pNoGo_FA = nNoGo_FA/nrow(NoGo_data)

# Mean and median RT
RTmeanGo_Hit = mean(Go_data$trial_rt[Go_data$trial_acc==1])
RTmedGo_Hit = median(Go_data$trial_rt[Go_data$trial_acc==1])

RTmeanNoGo_FA = mean(NoGo_data$trial_rt[NoGo_data$trial_acc==0])
RTmedNoGo_FA = median(NoGo_data$trial_rt[NoGo_data$trial_acc==0])


values <- list(RTmeanGo_Hit, RTmedGo_Hit, RTmeanNoGo_FA, RTmedNoGo_FA)

print(values)

```

```{r gng_summary}

# check if sum of block nAcc = total nAcc
summed_acc <- rowSums(gng_summary[, c("b1_nAcc", "b2_nAcc", "b3_nAcc", "b4_nAcc", "b5_nAcc")])
summed_acc == gng_summary$all_nAcc

# check if sum of all_nGo_Hit and all_nNoGo_Corr = total nAcc
summed_acc2 <- rowSums(gng_summary[, c("all_nGo_Hit","all_nNoGo_Corr")])
summed_acc2 == gng_summary$all_nAcc

# check if average of block pAcc = total nAcc
mean_acc <- rowMeans(gng_summary[, c("b1_pAcc", "b2_pAcc", "b3_pAcc", "b4_pAcc", "b5_pAcc")])
mean_acc == gng_summary$all_pAcc

# check if average of block pAcc = total nAcc
summed_nGoHit <- rowSums(gng_summary[, c("b1_nGo_Hit", "b2_nGo_Hit", "b3_nGo_Hit", "b4_nGo_Hit", "b5_nGo_Hit")])
summed_nGoHit == gng_summary$all_nGo_Hit

# check if average of block pAcc = total nAcc
summed_nGoMiss <- rowSums(gng_summary[, c("b1_nGo_Miss", "b2_nGo_Miss", "b3_nGo_Miss", "b4_nGo_Miss", "b5_nGo_Miss")])
summed_nGoMiss == gng_summary$all_nGo_Miss

```
