#!/bin/tcsh
#
#useage: G4_MVM  $1         $2             $3
#		        template    session   entire censor string (e.g., fd-0.9_by-block-7_3blocks)          
#                
#
# The purpose of this script run linear mixed effects model for
# ED by PS for Food and Brain study
# Written by Bari Fuchs Fall 2022

###################### set up initial variables  ###########################   
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO
 
##don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

###################### setup and check directories  ###########################   
cd ../../../
set bidsdir = "$cwd"

#set lev1 dir
set lev1_dir =  $bidsdir/derivatives/analyses/FoodCue-fmri/Level1GLM

#set dataframe dir
set df_dir = $bidsdir/derivatives/analyses/FoodCue-fmri/Level2GLM/Activation_Univariate/ses-${2}/

#set test directory
set test_dir = $bidsdir/derivatives/analyses/FoodCue-fmri/Level2GLM/Activation_Univariate/ses-${2}/LME

if ( ! -d $test_dir ) then
    mkdir -p $test_dir
endif

#set output name
set today = `date +%m-%d-%y`
 
# set censor criteria
set censor_str = $3

# set path to templates
set tpath = $bidsdir/derivatives/analyses/FoodCue-fmri/templates

#Get template specific variables
if ( "$1" == "MNI" ) then
        ##Get MNI template used in fmriprep
        set basedset = $tpath/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz
        set basedset_name = "tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz"
        # set string
        set temp = "MNI152NLin2009cAsym"
        set tempst = "MNI"
else
        #Get pediatric template used in fmriprep
        set basedset = $tpath/tpl-MNIPediatricAsym/cohort-3/tpl-MNIPediatricAsym_cohort-3_res-1_T1w.nii.gz
        set basedset_name = "tpl-MNIPediatricAsym_cohort-3_res-1_T1w.nii.gz"
        # set strings
	set temp = "MNIPediatricAsym_cohort-3"
	set tempst = "ped"
endif

#check to see if have 'Old' directory, 
#if do, check for and clean up old directories,
#if not, create all folders in that path    
#if ( -d $test_dir/MVM/Old ) then
#    set old_folders = `( ls -d $test_dir/MVM/*/ )`
#    foreach old ( $old_folders )
#        if ( "$old" != "$test_dir/MVM/Old/" ) then
#            mv $old $test_dir/MVM/Old
#        endif
#    end
#else
#     mkdir -p $test_dir/MVM/Old
#endif

#set map directory
set map_dir = $test_dir/${tempst}_${censor_str}_${today}

if ( ! -d $map_dir ) then
    mkdir -p $map_dir
endif

## Use this if masks are in fmriprep dir
#make mask with 80% of participants overlapping
if ( ! -f $map_dir/Session${2}_mask0.8_${today}+tlrc ) then
    3dmask_tool -input ${bidsdir}/derivatives/preprocessed/fmriprep/*/ses-1/func/foodcue_full_mask-${temp}*.nii \
            -prefix $map_dir/mask0.8_${today}+tlrc              \
            -frac 0.8
endif

## can use num_glt and glt to specify specific contrasts -- but I belive the main effects will be automatically reported

3dLME -prefix $map_dir/PSxED -jobs 10	\
    -model "ED*PS"  \
    -ranEff '~1'    \
    -SS_type 3     \
    -mask $map_dir/mask0.8_${today}+tlrc \
    -dataTable Subj	PS	ED	InputFile	\
        1	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-001/ped_fd-0.9_by-block-7/stats.sub-001+tlrc'[HighLarge#0_Coef]'	\
        1	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-001/ped_fd-0.9_by-block-7/stats.sub-001+tlrc'[HighSmall#0_Coef]'	\
        1	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-001/ped_fd-0.9_by-block-7/stats.sub-001+tlrc'[LowLarge#0_Coef]'	\
        1	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-001/ped_fd-0.9_by-block-7/stats.sub-001+tlrc'[LowSmall#0_Coef]'	\
        2	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-002/ped_fd-0.9_by-block-7/stats.sub-002+tlrc'[HighLarge#0_Coef]'	\
        2	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-002/ped_fd-0.9_by-block-7/stats.sub-002+tlrc'[HighSmall#0_Coef]'	\
        2	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-002/ped_fd-0.9_by-block-7/stats.sub-002+tlrc'[LowLarge#0_Coef]'	\
        2	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-002/ped_fd-0.9_by-block-7/stats.sub-002+tlrc'[LowSmall#0_Coef]'	\
        3	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-003/ped_fd-0.9_by-block-7/stats.sub-003+tlrc'[HighLarge#0_Coef]'	\
        3	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-003/ped_fd-0.9_by-block-7/stats.sub-003+tlrc'[HighSmall#0_Coef]'	\
        3	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-003/ped_fd-0.9_by-block-7/stats.sub-003+tlrc'[LowLarge#0_Coef]'	\
        3	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-003/ped_fd-0.9_by-block-7/stats.sub-003+tlrc'[LowSmall#0_Coef]'	\
        4	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-004/ped_fd-0.9_by-block-7/stats.sub-004+tlrc'[HighLarge#0_Coef]'	\
        4	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-004/ped_fd-0.9_by-block-7/stats.sub-004+tlrc'[HighSmall#0_Coef]'	\
        4	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-004/ped_fd-0.9_by-block-7/stats.sub-004+tlrc'[LowSmall#0_Coef]'	\
        5	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-005/ped_fd-0.9_by-block-7/stats.sub-005+tlrc'[HighLarge#0_Coef]'	\
        5	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-005/ped_fd-0.9_by-block-7/stats.sub-005+tlrc'[HighSmall#0_Coef]'	\
        5	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-005/ped_fd-0.9_by-block-7/stats.sub-005+tlrc'[LowLarge#0_Coef]'	\
        5	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-005/ped_fd-0.9_by-block-7/stats.sub-005+tlrc'[LowSmall#0_Coef]'	\
        7	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-007/ped_fd-0.9_by-block-7/stats.sub-007+tlrc'[LowLarge#0_Coef]'	\
        9	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-009/ped_fd-0.9_by-block-7/stats.sub-009+tlrc'[HighLarge#0_Coef]'	\
        9	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-009/ped_fd-0.9_by-block-7/stats.sub-009+tlrc'[HighSmall#0_Coef]'	\
        11	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-011/ped_fd-0.9_by-block-7/stats.sub-011+tlrc'[HighLarge#0_Coef]'	\
        11	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-011/ped_fd-0.9_by-block-7/stats.sub-011+tlrc'[HighSmall#0_Coef]'	\
        11	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-011/ped_fd-0.9_by-block-7/stats.sub-011+tlrc'[LowLarge#0_Coef]'	\
        11	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-011/ped_fd-0.9_by-block-7/stats.sub-011+tlrc'[LowSmall#0_Coef]'	\
        17	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-017/ped_fd-0.9_by-block-7/stats.sub-017+tlrc'[HighLarge#0_Coef]'	\
        17	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-017/ped_fd-0.9_by-block-7/stats.sub-017+tlrc'[HighSmall#0_Coef]'	\
        17	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-017/ped_fd-0.9_by-block-7/stats.sub-017+tlrc'[LowLarge#0_Coef]'	\
        17	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-017/ped_fd-0.9_by-block-7/stats.sub-017+tlrc'[LowSmall#0_Coef]'	\
        18	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-018/ped_fd-0.9_by-block-7/stats.sub-018+tlrc'[HighLarge#0_Coef]'	\
        18	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-018/ped_fd-0.9_by-block-7/stats.sub-018+tlrc'[HighSmall#0_Coef]'	\
        18	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-018/ped_fd-0.9_by-block-7/stats.sub-018+tlrc'[LowSmall#0_Coef]'	\
        19	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-019/ped_fd-0.9_by-block-7/stats.sub-019+tlrc'[LowLarge#0_Coef]'	\
        19	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-019/ped_fd-0.9_by-block-7/stats.sub-019+tlrc'[LowSmall#0_Coef]'	\
        20	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-020/ped_fd-0.9_by-block-7/stats.sub-020+tlrc'[HighLarge#0_Coef]'	\
        20	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-020/ped_fd-0.9_by-block-7/stats.sub-020+tlrc'[HighSmall#0_Coef]'	\
        20	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-020/ped_fd-0.9_by-block-7/stats.sub-020+tlrc'[LowLarge#0_Coef]'	\
        20	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-020/ped_fd-0.9_by-block-7/stats.sub-020+tlrc'[LowSmall#0_Coef]'	\
        21	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-021/ped_fd-0.9_by-block-7/stats.sub-021+tlrc'[HighLarge#0_Coef]'	\
        21	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-021/ped_fd-0.9_by-block-7/stats.sub-021+tlrc'[HighSmall#0_Coef]'	\
        21	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-021/ped_fd-0.9_by-block-7/stats.sub-021+tlrc'[LowLarge#0_Coef]'	\
        21	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-021/ped_fd-0.9_by-block-7/stats.sub-021+tlrc'[LowSmall#0_Coef]'	\
        22	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-022/ped_fd-0.9_by-block-7/stats.sub-022+tlrc'[HighLarge#0_Coef]'	\
        22	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-022/ped_fd-0.9_by-block-7/stats.sub-022+tlrc'[HighSmall#0_Coef]'	\
        22	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-022/ped_fd-0.9_by-block-7/stats.sub-022+tlrc'[LowLarge#0_Coef]'	\
        22	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-022/ped_fd-0.9_by-block-7/stats.sub-022+tlrc'[LowSmall#0_Coef]'	\
        23	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-023/ped_fd-0.9_by-block-7/stats.sub-023+tlrc'[HighLarge#0_Coef]'	\
        23	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-023/ped_fd-0.9_by-block-7/stats.sub-023+tlrc'[HighSmall#0_Coef]'	\
        23	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-023/ped_fd-0.9_by-block-7/stats.sub-023+tlrc'[LowLarge#0_Coef]'	\
        23	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-023/ped_fd-0.9_by-block-7/stats.sub-023+tlrc'[LowSmall#0_Coef]'	\
        26	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-026/ped_fd-0.9_by-block-7/stats.sub-026+tlrc'[HighLarge#0_Coef]'	\
        26	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-026/ped_fd-0.9_by-block-7/stats.sub-026+tlrc'[HighSmall#0_Coef]'	\
        26	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-026/ped_fd-0.9_by-block-7/stats.sub-026+tlrc'[LowLarge#0_Coef]'	\
        26	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-026/ped_fd-0.9_by-block-7/stats.sub-026+tlrc'[LowSmall#0_Coef]'	\
        28	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-028/ped_fd-0.9_by-block-7/stats.sub-028+tlrc'[HighLarge#0_Coef]'	\
        28	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-028/ped_fd-0.9_by-block-7/stats.sub-028+tlrc'[HighSmall#0_Coef]'	\
        28	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-028/ped_fd-0.9_by-block-7/stats.sub-028+tlrc'[LowLarge#0_Coef]'	\
        28	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-028/ped_fd-0.9_by-block-7/stats.sub-028+tlrc'[LowSmall#0_Coef]'	\
        30	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-030/ped_fd-0.9_by-block-7/stats.sub-030+tlrc'[HighLarge#0_Coef]'	\
        30	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-030/ped_fd-0.9_by-block-7/stats.sub-030+tlrc'[HighSmall#0_Coef]'	\
        30	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-030/ped_fd-0.9_by-block-7/stats.sub-030+tlrc'[LowLarge#0_Coef]'	\
        30	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-030/ped_fd-0.9_by-block-7/stats.sub-030+tlrc'[LowSmall#0_Coef]'	\
        31	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-031/ped_fd-0.9_by-block-7/stats.sub-031+tlrc'[HighLarge#0_Coef]'	\
        31	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-031/ped_fd-0.9_by-block-7/stats.sub-031+tlrc'[HighSmall#0_Coef]'	\
        31	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-031/ped_fd-0.9_by-block-7/stats.sub-031+tlrc'[LowLarge#0_Coef]'	\
        31	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-031/ped_fd-0.9_by-block-7/stats.sub-031+tlrc'[LowSmall#0_Coef]'	\
        33	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-033/ped_fd-0.9_by-block-7/stats.sub-033+tlrc'[HighLarge#0_Coef]'	\
        33	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-033/ped_fd-0.9_by-block-7/stats.sub-033+tlrc'[HighSmall#0_Coef]'	\
        33	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-033/ped_fd-0.9_by-block-7/stats.sub-033+tlrc'[LowLarge#0_Coef]'	\
        33	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-033/ped_fd-0.9_by-block-7/stats.sub-033+tlrc'[LowSmall#0_Coef]'	\
        35	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-035/ped_fd-0.9_by-block-7/stats.sub-035+tlrc'[HighSmall#0_Coef]'	\
        35	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-035/ped_fd-0.9_by-block-7/stats.sub-035+tlrc'[LowSmall#0_Coef]'	\
        36	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-036/ped_fd-0.9_by-block-7/stats.sub-036+tlrc'[HighLarge#0_Coef]'	\
        36	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-036/ped_fd-0.9_by-block-7/stats.sub-036+tlrc'[HighSmall#0_Coef]'	\
        36	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-036/ped_fd-0.9_by-block-7/stats.sub-036+tlrc'[LowLarge#0_Coef]'	\
        36	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-036/ped_fd-0.9_by-block-7/stats.sub-036+tlrc'[LowSmall#0_Coef]'	\
        37	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-037/ped_fd-0.9_by-block-7/stats.sub-037+tlrc'[HighLarge#0_Coef]'	\
        37	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-037/ped_fd-0.9_by-block-7/stats.sub-037+tlrc'[HighSmall#0_Coef]'	\
        37	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-037/ped_fd-0.9_by-block-7/stats.sub-037+tlrc'[LowLarge#0_Coef]'	\
        37	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-037/ped_fd-0.9_by-block-7/stats.sub-037+tlrc'[LowSmall#0_Coef]'	\
        38	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-038/ped_fd-0.9_by-block-7/stats.sub-038+tlrc'[HighLarge#0_Coef]'	\
        38	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-038/ped_fd-0.9_by-block-7/stats.sub-038+tlrc'[HighSmall#0_Coef]'	\
        38	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-038/ped_fd-0.9_by-block-7/stats.sub-038+tlrc'[LowLarge#0_Coef]'	\
        38	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-038/ped_fd-0.9_by-block-7/stats.sub-038+tlrc'[LowSmall#0_Coef]'	\
        39	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-039/ped_fd-0.9_by-block-7/stats.sub-039+tlrc'[HighLarge#0_Coef]'	\
        39	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-039/ped_fd-0.9_by-block-7/stats.sub-039+tlrc'[HighSmall#0_Coef]'	\
        39	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-039/ped_fd-0.9_by-block-7/stats.sub-039+tlrc'[LowLarge#0_Coef]'	\
        39	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-039/ped_fd-0.9_by-block-7/stats.sub-039+tlrc'[LowSmall#0_Coef]'	\
        40	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-040/ped_fd-0.9_by-block-7/stats.sub-040+tlrc'[HighLarge#0_Coef]'	\
        40	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-040/ped_fd-0.9_by-block-7/stats.sub-040+tlrc'[HighSmall#0_Coef]'	\
        40	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-040/ped_fd-0.9_by-block-7/stats.sub-040+tlrc'[LowLarge#0_Coef]'	\
        40	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-040/ped_fd-0.9_by-block-7/stats.sub-040+tlrc'[LowSmall#0_Coef]'	\
        41	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-041/ped_fd-0.9_by-block-7/stats.sub-041+tlrc'[HighLarge#0_Coef]'	\
        41	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-041/ped_fd-0.9_by-block-7/stats.sub-041+tlrc'[HighSmall#0_Coef]'	\
        41	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-041/ped_fd-0.9_by-block-7/stats.sub-041+tlrc'[LowLarge#0_Coef]'	\
        41	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-041/ped_fd-0.9_by-block-7/stats.sub-041+tlrc'[LowSmall#0_Coef]'	\
        43	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-043/ped_fd-0.9_by-block-7/stats.sub-043+tlrc'[HighLarge#0_Coef]'	\
        43	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-043/ped_fd-0.9_by-block-7/stats.sub-043+tlrc'[HighSmall#0_Coef]'	\
        43	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-043/ped_fd-0.9_by-block-7/stats.sub-043+tlrc'[LowLarge#0_Coef]'	\
        43	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-043/ped_fd-0.9_by-block-7/stats.sub-043+tlrc'[LowSmall#0_Coef]'	\
        45	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-045/ped_fd-0.9_by-block-7/stats.sub-045+tlrc'[HighLarge#0_Coef]'	\
        45	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-045/ped_fd-0.9_by-block-7/stats.sub-045+tlrc'[HighSmall#0_Coef]'	\
        45	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-045/ped_fd-0.9_by-block-7/stats.sub-045+tlrc'[LowLarge#0_Coef]'	\
        45	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-045/ped_fd-0.9_by-block-7/stats.sub-045+tlrc'[LowSmall#0_Coef]'	\
        47	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-047/ped_fd-0.9_by-block-7/stats.sub-047+tlrc'[HighLarge#0_Coef]'	\
        47	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-047/ped_fd-0.9_by-block-7/stats.sub-047+tlrc'[HighSmall#0_Coef]'	\
        47	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-047/ped_fd-0.9_by-block-7/stats.sub-047+tlrc'[LowLarge#0_Coef]'	\
        47	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-047/ped_fd-0.9_by-block-7/stats.sub-047+tlrc'[LowSmall#0_Coef]'	\
        48	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-048/ped_fd-0.9_by-block-7/stats.sub-048+tlrc'[HighLarge#0_Coef]'	\
        48	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-048/ped_fd-0.9_by-block-7/stats.sub-048+tlrc'[HighSmall#0_Coef]'	\
        48	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-048/ped_fd-0.9_by-block-7/stats.sub-048+tlrc'[LowLarge#0_Coef]'	\
        48	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-048/ped_fd-0.9_by-block-7/stats.sub-048+tlrc'[LowSmall#0_Coef]'	\
        49	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-049/ped_fd-0.9_by-block-7/stats.sub-049+tlrc'[LowLarge#0_Coef]'	\
        49	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-049/ped_fd-0.9_by-block-7/stats.sub-049+tlrc'[LowSmall#0_Coef]'	\
        51	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-051/ped_fd-0.9_by-block-7/stats.sub-051+tlrc'[HighLarge#0_Coef]'	\
        51	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-051/ped_fd-0.9_by-block-7/stats.sub-051+tlrc'[HighSmall#0_Coef]'	\
        51	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-051/ped_fd-0.9_by-block-7/stats.sub-051+tlrc'[LowLarge#0_Coef]'	\
        51	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-051/ped_fd-0.9_by-block-7/stats.sub-051+tlrc'[LowSmall#0_Coef]'	\
        54	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-054/ped_fd-0.9_by-block-7/stats.sub-054+tlrc'[HighLarge#0_Coef]'	\
        54	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-054/ped_fd-0.9_by-block-7/stats.sub-054+tlrc'[HighSmall#0_Coef]'	\
        54	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-054/ped_fd-0.9_by-block-7/stats.sub-054+tlrc'[LowLarge#0_Coef]'	\
        54	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-054/ped_fd-0.9_by-block-7/stats.sub-054+tlrc'[LowSmall#0_Coef]'	\
        55	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-055/ped_fd-0.9_by-block-7/stats.sub-055+tlrc'[HighLarge#0_Coef]'	\
        55	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-055/ped_fd-0.9_by-block-7/stats.sub-055+tlrc'[HighSmall#0_Coef]'	\
        55	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-055/ped_fd-0.9_by-block-7/stats.sub-055+tlrc'[LowLarge#0_Coef]'	\
        55	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-055/ped_fd-0.9_by-block-7/stats.sub-055+tlrc'[LowSmall#0_Coef]'	\
        56	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-056/ped_fd-0.9_by-block-7/stats.sub-056+tlrc'[HighLarge#0_Coef]'	\
        56	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-056/ped_fd-0.9_by-block-7/stats.sub-056+tlrc'[HighSmall#0_Coef]'	\
        56	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-056/ped_fd-0.9_by-block-7/stats.sub-056+tlrc'[LowLarge#0_Coef]'	\
        56	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-056/ped_fd-0.9_by-block-7/stats.sub-056+tlrc'[LowSmall#0_Coef]'	\
        58	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-058/ped_fd-0.9_by-block-7/stats.sub-058+tlrc'[HighLarge#0_Coef]'	\
        58	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-058/ped_fd-0.9_by-block-7/stats.sub-058+tlrc'[HighSmall#0_Coef]'	\
        58	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-058/ped_fd-0.9_by-block-7/stats.sub-058+tlrc'[LowLarge#0_Coef]'	\
        58	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-058/ped_fd-0.9_by-block-7/stats.sub-058+tlrc'[LowSmall#0_Coef]'	\
        68	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-068/ped_fd-0.9_by-block-7/stats.sub-068+tlrc'[HighSmall#0_Coef]'	\
        68	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-068/ped_fd-0.9_by-block-7/stats.sub-068+tlrc'[LowLarge#0_Coef]'	\
        68	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-068/ped_fd-0.9_by-block-7/stats.sub-068+tlrc'[LowSmall#0_Coef]'	\
        70	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-070/ped_fd-0.9_by-block-7/stats.sub-070+tlrc'[HighLarge#0_Coef]'	\
        70	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-070/ped_fd-0.9_by-block-7/stats.sub-070+tlrc'[HighSmall#0_Coef]'	\
        70	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-070/ped_fd-0.9_by-block-7/stats.sub-070+tlrc'[LowLarge#0_Coef]'	\
        70	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-070/ped_fd-0.9_by-block-7/stats.sub-070+tlrc'[LowSmall#0_Coef]'	\
        71	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-071/ped_fd-0.9_by-block-7/stats.sub-071+tlrc'[HighLarge#0_Coef]'	\
        71	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-071/ped_fd-0.9_by-block-7/stats.sub-071+tlrc'[HighSmall#0_Coef]'	\
        71	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-071/ped_fd-0.9_by-block-7/stats.sub-071+tlrc'[LowLarge#0_Coef]'	\
        71	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-071/ped_fd-0.9_by-block-7/stats.sub-071+tlrc'[LowSmall#0_Coef]'	\
        73	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-073/ped_fd-0.9_by-block-7/stats.sub-073+tlrc'[HighLarge#0_Coef]'	\
        73	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-073/ped_fd-0.9_by-block-7/stats.sub-073+tlrc'[HighSmall#0_Coef]'	\
        73	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-073/ped_fd-0.9_by-block-7/stats.sub-073+tlrc'[LowLarge#0_Coef]'	\
        73	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-073/ped_fd-0.9_by-block-7/stats.sub-073+tlrc'[LowSmall#0_Coef]'	\
        74	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-074/ped_fd-0.9_by-block-7/stats.sub-074+tlrc'[HighLarge#0_Coef]'	\
        74	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-074/ped_fd-0.9_by-block-7/stats.sub-074+tlrc'[HighSmall#0_Coef]'	\
        74	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-074/ped_fd-0.9_by-block-7/stats.sub-074+tlrc'[LowLarge#0_Coef]'	\
        74	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-074/ped_fd-0.9_by-block-7/stats.sub-074+tlrc'[LowSmall#0_Coef]'	\
        75	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-075/ped_fd-0.9_by-block-7/stats.sub-075+tlrc'[HighSmall#0_Coef]'	\
        75	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-075/ped_fd-0.9_by-block-7/stats.sub-075+tlrc'[LowLarge#0_Coef]'	\
        75	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-075/ped_fd-0.9_by-block-7/stats.sub-075+tlrc'[LowSmall#0_Coef]'	\
        78	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-078/ped_fd-0.9_by-block-7/stats.sub-078+tlrc'[HighLarge#0_Coef]'	\
        78	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-078/ped_fd-0.9_by-block-7/stats.sub-078+tlrc'[HighSmall#0_Coef]'	\
        78	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-078/ped_fd-0.9_by-block-7/stats.sub-078+tlrc'[LowSmall#0_Coef]'	\
        80	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-080/ped_fd-0.9_by-block-7/stats.sub-080+tlrc'[HighLarge#0_Coef]'	\
        80	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-080/ped_fd-0.9_by-block-7/stats.sub-080+tlrc'[HighSmall#0_Coef]'	\
        80	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-080/ped_fd-0.9_by-block-7/stats.sub-080+tlrc'[LowLarge#0_Coef]'	\
        80	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-080/ped_fd-0.9_by-block-7/stats.sub-080+tlrc'[LowSmall#0_Coef]'	\
        83	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-083/ped_fd-0.9_by-block-7/stats.sub-083+tlrc'[HighLarge#0_Coef]'	\
        83	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-083/ped_fd-0.9_by-block-7/stats.sub-083+tlrc'[HighSmall#0_Coef]'	\
        83	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-083/ped_fd-0.9_by-block-7/stats.sub-083+tlrc'[LowLarge#0_Coef]'	\
        83	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-083/ped_fd-0.9_by-block-7/stats.sub-083+tlrc'[LowSmall#0_Coef]'	\
        84	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-084/ped_fd-0.9_by-block-7/stats.sub-084+tlrc'[HighLarge#0_Coef]'	\
        84	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-084/ped_fd-0.9_by-block-7/stats.sub-084+tlrc'[LowSmall#0_Coef]'	\
        89	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-089/ped_fd-0.9_by-block-7/stats.sub-089+tlrc'[HighLarge#0_Coef]'	\
        89	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-089/ped_fd-0.9_by-block-7/stats.sub-089+tlrc'[HighSmall#0_Coef]'	\
        89	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-089/ped_fd-0.9_by-block-7/stats.sub-089+tlrc'[LowLarge#0_Coef]'	\
        89	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-089/ped_fd-0.9_by-block-7/stats.sub-089+tlrc'[LowSmall#0_Coef]'	\
        90	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-090/ped_fd-0.9_by-block-7/stats.sub-090+tlrc'[HighLarge#0_Coef]'	\
        90	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-090/ped_fd-0.9_by-block-7/stats.sub-090+tlrc'[HighSmall#0_Coef]'	\
        90	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-090/ped_fd-0.9_by-block-7/stats.sub-090+tlrc'[LowLarge#0_Coef]'	\
        90	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-090/ped_fd-0.9_by-block-7/stats.sub-090+tlrc'[LowSmall#0_Coef]'	\
        93	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-093/ped_fd-0.9_by-block-7/stats.sub-093+tlrc'[HighLarge#0_Coef]'	\
        93	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-093/ped_fd-0.9_by-block-7/stats.sub-093+tlrc'[HighSmall#0_Coef]'	\
        93	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-093/ped_fd-0.9_by-block-7/stats.sub-093+tlrc'[LowSmall#0_Coef]'	\
        94	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-094/ped_fd-0.9_by-block-7/stats.sub-094+tlrc'[HighLarge#0_Coef]'	\
        94	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-094/ped_fd-0.9_by-block-7/stats.sub-094+tlrc'[HighSmall#0_Coef]'	\
        94	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-094/ped_fd-0.9_by-block-7/stats.sub-094+tlrc'[LowLarge#0_Coef]'	\
        94	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-094/ped_fd-0.9_by-block-7/stats.sub-094+tlrc'[LowSmall#0_Coef]'	\
        95	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-095/ped_fd-0.9_by-block-7/stats.sub-095+tlrc'[HighLarge#0_Coef]'	\
        95	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-095/ped_fd-0.9_by-block-7/stats.sub-095+tlrc'[HighSmall#0_Coef]'	\
        95	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-095/ped_fd-0.9_by-block-7/stats.sub-095+tlrc'[LowLarge#0_Coef]'	\
        95	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-095/ped_fd-0.9_by-block-7/stats.sub-095+tlrc'[LowSmall#0_Coef]'	\
        96	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-096/ped_fd-0.9_by-block-7/stats.sub-096+tlrc'[HighLarge#0_Coef]'	\
        96	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-096/ped_fd-0.9_by-block-7/stats.sub-096+tlrc'[HighSmall#0_Coef]'	\
        96	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-096/ped_fd-0.9_by-block-7/stats.sub-096+tlrc'[LowLarge#0_Coef]'	\
        96	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-096/ped_fd-0.9_by-block-7/stats.sub-096+tlrc'[LowSmall#0_Coef]'	\
        101	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-101/ped_fd-0.9_by-block-7/stats.sub-101+tlrc'[HighLarge#0_Coef]'	\
        101	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-101/ped_fd-0.9_by-block-7/stats.sub-101+tlrc'[HighSmall#0_Coef]'	\
        101	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-101/ped_fd-0.9_by-block-7/stats.sub-101+tlrc'[LowLarge#0_Coef]'	\
        101	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-101/ped_fd-0.9_by-block-7/stats.sub-101+tlrc'[LowSmall#0_Coef]'	\
        103	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-103/ped_fd-0.9_by-block-7/stats.sub-103+tlrc'[HighLarge#0_Coef]'	\
        103	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-103/ped_fd-0.9_by-block-7/stats.sub-103+tlrc'[HighSmall#0_Coef]'	\
        103	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-103/ped_fd-0.9_by-block-7/stats.sub-103+tlrc'[LowLarge#0_Coef]'	\
        103	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-103/ped_fd-0.9_by-block-7/stats.sub-103+tlrc'[LowSmall#0_Coef]'	\
        104	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-104/ped_fd-0.9_by-block-7/stats.sub-104+tlrc'[HighLarge#0_Coef]'	\
        104	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-104/ped_fd-0.9_by-block-7/stats.sub-104+tlrc'[HighSmall#0_Coef]'	\
        104	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-104/ped_fd-0.9_by-block-7/stats.sub-104+tlrc'[LowLarge#0_Coef]'	\
        104	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-104/ped_fd-0.9_by-block-7/stats.sub-104+tlrc'[LowSmall#0_Coef]'	\
        105	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-105/ped_fd-0.9_by-block-7/stats.sub-105+tlrc'[HighLarge#0_Coef]'	\
        105	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-105/ped_fd-0.9_by-block-7/stats.sub-105+tlrc'[HighSmall#0_Coef]'	\
        105	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-105/ped_fd-0.9_by-block-7/stats.sub-105+tlrc'[LowLarge#0_Coef]'	\
        105	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-105/ped_fd-0.9_by-block-7/stats.sub-105+tlrc'[LowSmall#0_Coef]'	\
        109	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-109/ped_fd-0.9_by-block-7/stats.sub-109+tlrc'[HighLarge#0_Coef]'	\
        109	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-109/ped_fd-0.9_by-block-7/stats.sub-109+tlrc'[HighSmall#0_Coef]'	\
        109	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-109/ped_fd-0.9_by-block-7/stats.sub-109+tlrc'[LowLarge#0_Coef]'	\
        109	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-109/ped_fd-0.9_by-block-7/stats.sub-109+tlrc'[LowSmall#0_Coef]'	\
        110	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-110/ped_fd-0.9_by-block-7/stats.sub-110+tlrc'[HighLarge#0_Coef]'	\
        110	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-110/ped_fd-0.9_by-block-7/stats.sub-110+tlrc'[HighSmall#0_Coef]'	\
        110	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-110/ped_fd-0.9_by-block-7/stats.sub-110+tlrc'[LowLarge#0_Coef]'	\
        110	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-110/ped_fd-0.9_by-block-7/stats.sub-110+tlrc'[LowSmall#0_Coef]'	\
        111	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-111/ped_fd-0.9_by-block-7/stats.sub-111+tlrc'[HighLarge#0_Coef]'	\
        111	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-111/ped_fd-0.9_by-block-7/stats.sub-111+tlrc'[HighSmall#0_Coef]'	\
        111	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-111/ped_fd-0.9_by-block-7/stats.sub-111+tlrc'[LowLarge#0_Coef]'	\
        111	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-111/ped_fd-0.9_by-block-7/stats.sub-111+tlrc'[LowSmall#0_Coef]'	\
        114	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-114/ped_fd-0.9_by-block-7/stats.sub-114+tlrc'[HighSmall#0_Coef]'	\
        114	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-114/ped_fd-0.9_by-block-7/stats.sub-114+tlrc'[LowSmall#0_Coef]'	\
        115	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-115/ped_fd-0.9_by-block-7/stats.sub-115+tlrc'[HighLarge#0_Coef]'	\
        115	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-115/ped_fd-0.9_by-block-7/stats.sub-115+tlrc'[HighSmall#0_Coef]'	\
        115	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-115/ped_fd-0.9_by-block-7/stats.sub-115+tlrc'[LowLarge#0_Coef]'	\
        116	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-116/ped_fd-0.9_by-block-7/stats.sub-116+tlrc'[HighLarge#0_Coef]'	\
        116	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-116/ped_fd-0.9_by-block-7/stats.sub-116+tlrc'[HighSmall#0_Coef]'	\
        116	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-116/ped_fd-0.9_by-block-7/stats.sub-116+tlrc'[LowLarge#0_Coef]'	\
        116	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-116/ped_fd-0.9_by-block-7/stats.sub-116+tlrc'[LowSmall#0_Coef]'	\
        118	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-118/ped_fd-0.9_by-block-7/stats.sub-118+tlrc'[HighLarge#0_Coef]'	\
        118	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-118/ped_fd-0.9_by-block-7/stats.sub-118+tlrc'[HighSmall#0_Coef]'	\
        118	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-118/ped_fd-0.9_by-block-7/stats.sub-118+tlrc'[LowLarge#0_Coef]'	\
        118	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-118/ped_fd-0.9_by-block-7/stats.sub-118+tlrc'[LowSmall#0_Coef]'	\
        119	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-119/ped_fd-0.9_by-block-7/stats.sub-119+tlrc'[HighLarge#0_Coef]'	\
        119	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-119/ped_fd-0.9_by-block-7/stats.sub-119+tlrc'[HighSmall#0_Coef]'	\
        119	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-119/ped_fd-0.9_by-block-7/stats.sub-119+tlrc'[LowLarge#0_Coef]'	\
        119	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-119/ped_fd-0.9_by-block-7/stats.sub-119+tlrc'[LowSmall#0_Coef]'	\
        120	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-120/ped_fd-0.9_by-block-7/stats.sub-120+tlrc'[HighLarge#0_Coef]'	\
        120	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-120/ped_fd-0.9_by-block-7/stats.sub-120+tlrc'[HighSmall#0_Coef]'	\
        120	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-120/ped_fd-0.9_by-block-7/stats.sub-120+tlrc'[LowLarge#0_Coef]'	\
        120	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-120/ped_fd-0.9_by-block-7/stats.sub-120+tlrc'[LowSmall#0_Coef]'	\
        121	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-121/ped_fd-0.9_by-block-7/stats.sub-121+tlrc'[HighLarge#0_Coef]'	\
        121	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-121/ped_fd-0.9_by-block-7/stats.sub-121+tlrc'[HighSmall#0_Coef]'	\
        121	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-121/ped_fd-0.9_by-block-7/stats.sub-121+tlrc'[LowLarge#0_Coef]'	\
        121	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-121/ped_fd-0.9_by-block-7/stats.sub-121+tlrc'[LowSmall#0_Coef]'	\
        123	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-123/ped_fd-0.9_by-block-7/stats.sub-123+tlrc'[HighLarge#0_Coef]'	\
        123	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-123/ped_fd-0.9_by-block-7/stats.sub-123+tlrc'[HighSmall#0_Coef]'	\
        123	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-123/ped_fd-0.9_by-block-7/stats.sub-123+tlrc'[LowLarge#0_Coef]'	\
        124	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-124/ped_fd-0.9_by-block-7/stats.sub-124+tlrc'[HighSmall#0_Coef]'	\
        126	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-126/ped_fd-0.9_by-block-7/stats.sub-126+tlrc'[HighLarge#0_Coef]'	\
        126	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-126/ped_fd-0.9_by-block-7/stats.sub-126+tlrc'[HighSmall#0_Coef]'	\
        126	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-126/ped_fd-0.9_by-block-7/stats.sub-126+tlrc'[LowLarge#0_Coef]'	\
        126	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-126/ped_fd-0.9_by-block-7/stats.sub-126+tlrc'[LowSmall#0_Coef]'	\
        127	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-127/ped_fd-0.9_by-block-7/stats.sub-127+tlrc'[LowLarge#0_Coef]'	\
        127	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-127/ped_fd-0.9_by-block-7/stats.sub-127+tlrc'[LowSmall#0_Coef]'	\
        128	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-128/ped_fd-0.9_by-block-7/stats.sub-128+tlrc'[HighLarge#0_Coef]'	\
        128	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-128/ped_fd-0.9_by-block-7/stats.sub-128+tlrc'[HighSmall#0_Coef]'	\
        128	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-128/ped_fd-0.9_by-block-7/stats.sub-128+tlrc'[LowLarge#0_Coef]'	\
        128	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-128/ped_fd-0.9_by-block-7/stats.sub-128+tlrc'[LowSmall#0_Coef]'	\
        129	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-129/ped_fd-0.9_by-block-7/stats.sub-129+tlrc'[HighLarge#0_Coef]'	\
        129	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-129/ped_fd-0.9_by-block-7/stats.sub-129+tlrc'[HighSmall#0_Coef]'	\
        129	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-129/ped_fd-0.9_by-block-7/stats.sub-129+tlrc'[LowLarge#0_Coef]'	\
        129	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-129/ped_fd-0.9_by-block-7/stats.sub-129+tlrc'[LowSmall#0_Coef]'	\
        131	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-131/ped_fd-0.9_by-block-7/stats.sub-131+tlrc'[HighLarge#0_Coef]'	\
        131	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-131/ped_fd-0.9_by-block-7/stats.sub-131+tlrc'[HighSmall#0_Coef]'	\
        131	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-131/ped_fd-0.9_by-block-7/stats.sub-131+tlrc'[LowLarge#0_Coef]'	\
        131	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-131/ped_fd-0.9_by-block-7/stats.sub-131+tlrc'[LowSmall#0_Coef]'	\
        132	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-132/ped_fd-0.9_by-block-7/stats.sub-132+tlrc'[HighLarge#0_Coef]'	\
        132	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-132/ped_fd-0.9_by-block-7/stats.sub-132+tlrc'[HighSmall#0_Coef]'	\
        132	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-132/ped_fd-0.9_by-block-7/stats.sub-132+tlrc'[LowLarge#0_Coef]'	\
        132	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-132/ped_fd-0.9_by-block-7/stats.sub-132+tlrc'[LowSmall#0_Coef]'	\
        133	High	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-133/ped_fd-0.9_by-block-7/stats.sub-133+tlrc'[HighLarge#0_Coef]'	\
        133	High	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-133/ped_fd-0.9_by-block-7/stats.sub-133+tlrc'[HighSmall#0_Coef]'	\
        133	Low	Large	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-133/ped_fd-0.9_by-block-7/stats.sub-133+tlrc'[LowLarge#0_Coef]'	\
        133	Low	Small	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-133/ped_fd-0.9_by-block-7/stats.sub-133+tlrc'[LowSmall#0_Coef]	
    
#  end

if ( "$tpath" == '' ) then
     echo "***** Failed to find $basedset :("
     exit 1
else
    if ( ! -f $map_dir/$basedset ) then
       cp $tpath/$basedset $map_dir
    endif
endif
