#!/bin/tcsh
#
#useage: G5b_

# The purpose of this script is to extrat beta values for a previously defined cluster
# Written by Bari Fuchs Fall 2022
###################### set up initial variables  ###########################   
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO
 
##don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

###################### setup and check directories  ###########################   
cd ../../../
set bidsdir = "$cwd"

#set lev1 dir
set lev1_dir =  $bidsdir/derivatives/analyses/foodcue-paper2/level1

#set level 2
set lev2_dir = $bidsdir/derivatives/analyses/foodcue-paper2/level2

#set test directory
set test_dir = $lev2_dir/1sampleT_byED

#set map directory
set map_dir = $test_dir/ped_fd-0.9_b20_3runs_noGSR_02-01-23

if ( ! -d $map_dir ) then
	echo "failed to find $map_dir"
	exit
endif

# delete beta text file 
if ( -f $map_dir/cerebellum_betas.txt ) then
	rm $map_dir/cerebellum_betas.txt
endif

# add headers to new file
echo sub ' \t ' led_large-small >> $map_dir/cerebellum_betas.txt

# loop through subjects
foreach i ( `cat $lev2_dir/index_all_fd-0.9_b20_3runs.txt ` )
	set sub = $i
	set beta = `3dmaskave -mask $map_dir/cerebellum_led-g-p001+tlrc. $lev1_dir/sub-$sub/ped_fd-0.9_b20_noGSR/stats.sub-$sub+tlrc'[LowLarge-Small_GLT#0_Coef]'`
	echo $sub ' \t ' $beta >> $map_dir/cerebellum_betas.txt 
end
