#!/bin/tcsh
#
#useage: G4_MVM  $1         $2             $3
#		        template    session   entire censor string (e.g., fd-0.9_by-block-7_3blocks, fd-0.9_b20_3runs)          
#                
#
# The purpose of this script run linear mixed effects model for
# ED contrast by PS and Risk for Food and Brain study
# Written by Bari Fuchs Fall 2022

###################### set up initial variables  ###########################   
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO
 
##don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

###################### setup and check directories  ###########################   
cd ../../
set bidsdir = "$cwd"

#set lev1 dir
set lev1_dir =  $bidsdir/derivatives/analyses/FoodCue-fmri/Level1GLM

#set dataframe dir
set df_dir = $bidsdir/derivatives/analyses/FoodCue-fmri/Level2GLM/Activation_Univariate/ses-${2}/

#set test directory
set test_dir = $bidsdir/derivatives/analyses/FoodCue-fmri/Level2GLM/Activation_Univariate/ses-${2}/MVM

if ( ! -d $test_dir ) then
    mkdir -p $test_dir
endif

#set output name
set today = `date +%m-%d-%y`
 
# set censor criteria
set censor_str = $3

# set path to templates
set tpath = $bidsdir/derivatives/analyses/FoodCue-fmri/templates

#Get template specific variables
if ( "$1" == "MNI" ) then
        ##Get MNI template used in fmriprep
        set basedset = $tpath/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz
        set basedset_name = "tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz"
        # set string
        set temp = "MNI152NLin2009cAsym"
        set tempst = "MNI"
else
        #Get pediatric template used in fmriprep
        set basedset = $tpath/tpl-MNIPediatricAsym/cohort-3/tpl-MNIPediatricAsym_cohort-3_res-1_T1w.nii.gz
        set basedset_name = "tpl-MNIPediatricAsym_cohort-3_res-1_T1w.nii.gz"
        # set strings
	set temp = "MNIPediatricAsym_cohort-3"
	set tempst = "ped"
endif

#check to see if have 'Old' directory, 
#if do, check for and clean up old directories,
#if not, create all folders in that path    
#if ( -d $test_dir/MVM/Old ) then
#    set old_folders = `( ls -d $test_dir/MVM/*/ )`
#    foreach old ( $old_folders )
#        if ( "$old" != "$test_dir/MVM/Old/" ) then
#            mv $old $test_dir/MVM/Old
#        endif
#    end
#else
#     mkdir -p $test_dir/MVM/Old
#endif

#set map directory
set map_dir = $test_dir/${tempst}_${censor_str}_${today}_2

if ( ! -d $map_dir ) then
    mkdir -p $map_dir
endif

# set datatable name
set data_table = dataframe-EDcon-${censor_str}.txt

#copy datatable into map directory
cp $df_dir/$data_table $map_dir 

## Use this if masks are in fmriprep dir
#make mask with 80% of participants overlapping
if ( ! -f $map_dir/Session${2}_mask0.8_${today}+tlrc ) then
    3dmask_tool -input ${bidsdir}/derivatives/preprocessed/fmriprep/*/ses-1/func/foodcue_full_mask-${temp}*.nii \
            -prefix $map_dir/mask0.8_${today}+tlrc              \
            -frac 0.8
endif

## can use num_glt and glt to specify specific contrasts -- but I belive the main effects will be automatically reported

3dMVM -prefix $map_dir/MVM_${today}_EDcontrast -jobs 10	\
      -wsVars PS					\
      -bsVars risk	    \
      -SS_type 3 	  \
      -GES 		\
      -mask $map_dir/mask0.8_${today}+tlrc       \
      -dataTable Subj	PS	risk	InputFile	\
        001	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-001/ped_fd-0.9_b20/stats.sub-001+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        001	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-001/ped_fd-0.9_b20/stats.sub-001+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        002	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-002/ped_fd-0.9_b20/stats.sub-002+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        002	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-002/ped_fd-0.9_b20/stats.sub-002+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        003	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-003/ped_fd-0.9_b20/stats.sub-003+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        003	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-003/ped_fd-0.9_b20/stats.sub-003+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        004	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-004/ped_fd-0.9_b20/stats.sub-004+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        004	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-004/ped_fd-0.9_b20/stats.sub-004+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        005	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-005/ped_fd-0.9_b20/stats.sub-005+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        005	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-005/ped_fd-0.9_b20/stats.sub-005+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        011	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-011/ped_fd-0.9_b20/stats.sub-011+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        011	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-011/ped_fd-0.9_b20/stats.sub-011+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        017	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-017/ped_fd-0.9_b20/stats.sub-017+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        017	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-017/ped_fd-0.9_b20/stats.sub-017+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        020	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-020/ped_fd-0.9_b20/stats.sub-020+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        020	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-020/ped_fd-0.9_b20/stats.sub-020+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        021	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-021/ped_fd-0.9_b20/stats.sub-021+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        021	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-021/ped_fd-0.9_b20/stats.sub-021+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        022	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-022/ped_fd-0.9_b20/stats.sub-022+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        022	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-022/ped_fd-0.9_b20/stats.sub-022+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        023	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-023/ped_fd-0.9_b20/stats.sub-023+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        023	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-023/ped_fd-0.9_b20/stats.sub-023+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        026	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-026/ped_fd-0.9_b20/stats.sub-026+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        026	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-026/ped_fd-0.9_b20/stats.sub-026+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        028	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-028/ped_fd-0.9_b20/stats.sub-028+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        028	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-028/ped_fd-0.9_b20/stats.sub-028+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        030	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-030/ped_fd-0.9_b20/stats.sub-030+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        030	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-030/ped_fd-0.9_b20/stats.sub-030+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        031	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-031/ped_fd-0.9_b20/stats.sub-031+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        031	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-031/ped_fd-0.9_b20/stats.sub-031+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        033	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-033/ped_fd-0.9_b20/stats.sub-033+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        033	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-033/ped_fd-0.9_b20/stats.sub-033+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        036	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-036/ped_fd-0.9_b20/stats.sub-036+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        036	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-036/ped_fd-0.9_b20/stats.sub-036+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        037	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-037/ped_fd-0.9_b20/stats.sub-037+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        037	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-037/ped_fd-0.9_b20/stats.sub-037+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        038	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-038/ped_fd-0.9_b20/stats.sub-038+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        038	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-038/ped_fd-0.9_b20/stats.sub-038+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        039	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-039/ped_fd-0.9_b20/stats.sub-039+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        039	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-039/ped_fd-0.9_b20/stats.sub-039+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        040	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-040/ped_fd-0.9_b20/stats.sub-040+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        040	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-040/ped_fd-0.9_b20/stats.sub-040+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        041	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-041/ped_fd-0.9_b20/stats.sub-041+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        041	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-041/ped_fd-0.9_b20/stats.sub-041+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        043	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-043/ped_fd-0.9_b20/stats.sub-043+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        043	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-043/ped_fd-0.9_b20/stats.sub-043+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        045	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-045/ped_fd-0.9_b20/stats.sub-045+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        045	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-045/ped_fd-0.9_b20/stats.sub-045+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        047	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-047/ped_fd-0.9_b20/stats.sub-047+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        047	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-047/ped_fd-0.9_b20/stats.sub-047+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        048	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-048/ped_fd-0.9_b20/stats.sub-048+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        048	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-048/ped_fd-0.9_b20/stats.sub-048+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        049     Large   Low     /gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-049/ped_fd-0.9_b20/stats.sub-049+tlrc'[LargeHigh-Low_GLT#0_Coef]'   \
        049     Small   Low     /gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-049/ped_fd-0.9_b20/stats.sub-049+tlrc'[SmallHigh-Low_GLT#0_Coef]'   \
        051	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-051/ped_fd-0.9_b20/stats.sub-051+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        051	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-051/ped_fd-0.9_b20/stats.sub-051+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        054	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-054/ped_fd-0.9_b20/stats.sub-054+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        054	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-054/ped_fd-0.9_b20/stats.sub-054+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        055	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-055/ped_fd-0.9_b20/stats.sub-055+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        055	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-055/ped_fd-0.9_b20/stats.sub-055+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        056	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-056/ped_fd-0.9_b20/stats.sub-056+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        056	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-056/ped_fd-0.9_b20/stats.sub-056+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        058	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-058/ped_fd-0.9_b20/stats.sub-058+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        058	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-058/ped_fd-0.9_b20/stats.sub-058+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        070	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-070/ped_fd-0.9_b20/stats.sub-070+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        070	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-070/ped_fd-0.9_b20/stats.sub-070+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        071	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-071/ped_fd-0.9_b20/stats.sub-071+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        071	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-071/ped_fd-0.9_b20/stats.sub-071+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        073	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-073/ped_fd-0.9_b20/stats.sub-073+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        073	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-073/ped_fd-0.9_b20/stats.sub-073+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        074	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-074/ped_fd-0.9_b20/stats.sub-074+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        074	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-074/ped_fd-0.9_b20/stats.sub-074+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        075	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-075/ped_fd-0.9_b20/stats.sub-075+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        075	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-075/ped_fd-0.9_b20/stats.sub-075+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        078	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-078/ped_fd-0.9_b20/stats.sub-078+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        078	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-078/ped_fd-0.9_b20/stats.sub-078+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        080	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-080/ped_fd-0.9_b20/stats.sub-080+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        080	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-080/ped_fd-0.9_b20/stats.sub-080+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        083	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-083/ped_fd-0.9_b20/stats.sub-083+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        083	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-083/ped_fd-0.9_b20/stats.sub-083+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        084	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-084/ped_fd-0.9_b20/stats.sub-084+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        084	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-084/ped_fd-0.9_b20/stats.sub-084+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        089	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-089/ped_fd-0.9_b20/stats.sub-089+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        089	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-089/ped_fd-0.9_b20/stats.sub-089+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        090	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-090/ped_fd-0.9_b20/stats.sub-090+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        090	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-090/ped_fd-0.9_b20/stats.sub-090+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        094	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-094/ped_fd-0.9_b20/stats.sub-094+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        094	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-094/ped_fd-0.9_b20/stats.sub-094+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        095	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-095/ped_fd-0.9_b20/stats.sub-095+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        095	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-095/ped_fd-0.9_b20/stats.sub-095+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        096	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-096/ped_fd-0.9_b20/stats.sub-096+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        096	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-096/ped_fd-0.9_b20/stats.sub-096+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        101	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-101/ped_fd-0.9_b20/stats.sub-101+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        101	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-101/ped_fd-0.9_b20/stats.sub-101+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        103	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-103/ped_fd-0.9_b20/stats.sub-103+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        103	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-103/ped_fd-0.9_b20/stats.sub-103+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        104	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-104/ped_fd-0.9_b20/stats.sub-104+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        104	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-104/ped_fd-0.9_b20/stats.sub-104+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        105	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-105/ped_fd-0.9_b20/stats.sub-105+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        105	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-105/ped_fd-0.9_b20/stats.sub-105+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        109	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-109/ped_fd-0.9_b20/stats.sub-109+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        109	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-109/ped_fd-0.9_b20/stats.sub-109+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        110	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-110/ped_fd-0.9_b20/stats.sub-110+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        110	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-110/ped_fd-0.9_b20/stats.sub-110+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        111	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-111/ped_fd-0.9_b20/stats.sub-111+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        111	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-111/ped_fd-0.9_b20/stats.sub-111+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        116	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-116/ped_fd-0.9_b20/stats.sub-116+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        116	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-116/ped_fd-0.9_b20/stats.sub-116+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        118	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-118/ped_fd-0.9_b20/stats.sub-118+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        118	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-118/ped_fd-0.9_b20/stats.sub-118+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        119	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-119/ped_fd-0.9_b20/stats.sub-119+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        119	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-119/ped_fd-0.9_b20/stats.sub-119+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        120	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-120/ped_fd-0.9_b20/stats.sub-120+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        120	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-120/ped_fd-0.9_b20/stats.sub-120+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        121	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-121/ped_fd-0.9_b20/stats.sub-121+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        121	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-121/ped_fd-0.9_b20/stats.sub-121+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        126	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-126/ped_fd-0.9_b20/stats.sub-126+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        126	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-126/ped_fd-0.9_b20/stats.sub-126+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        128	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-128/ped_fd-0.9_b20/stats.sub-128+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        128	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-128/ped_fd-0.9_b20/stats.sub-128+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        129	Large	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-129/ped_fd-0.9_b20/stats.sub-129+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        129	Small	Low	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-129/ped_fd-0.9_b20/stats.sub-129+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        131	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-131/ped_fd-0.9_b20/stats.sub-131+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        131	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-131/ped_fd-0.9_b20/stats.sub-131+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        132	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-132/ped_fd-0.9_b20/stats.sub-132+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        132	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-132/ped_fd-0.9_b20/stats.sub-132+tlrc'[SmallHigh-Low_GLT#0_Coef]'	\
        133	Large	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-133/ped_fd-0.9_b20/stats.sub-133+tlrc'[LargeHigh-Low_GLT#0_Coef]'	\
        133	Small	High	/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS/derivatives/analyses/FoodCue-fmri/Level1GLM/sub-133/ped_fd-0.9_b20/stats.sub-133+tlrc'[SmallHigh-Low_GLT#0_Coef]'


    
#  end

if ( "$tpath" == '' ) then
     echo "***** Failed to find $basedset :("
     exit 1
else
    if ( ! -f $map_dir/$basedset ) then
       cp $tpath/$basedset $map_dir
    endif
endif
