#!/bin/tcsh
#
#useage: Gopt_2sampleT_ClusterMainContrasts   $1         $2         $3     $4     $5
#					    session	 motst     pvalue   k   overwrite?
#
# The purpose of this script is to create cluster reports, maps, and threshholded
# maps for all conditions of interest. Written Fall 2019 Alaina Pearce.
# $1: 1 or 2
# $2: r10b20 or r20b20 (or other motst used in future)
# $3: pvalue
# $4: cluster sizw
# $5: Y or noting -- want to overwrite?
###################### set up initial variables  ###########################   
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES

#dont try version checks
setenv ANFI_VRSION_CHECK NO

##don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

###################### setup and check directories  ###########################   
#go to and set AFNI main directory
cd ..
set topdir = "$cwd"

#input arguments
set motst = $2
set pvalue = $3
set k = $4
set overwrite = $5

#set model dir
set model_dir = $topdir/ImagingData/Level2GLM/Activation_Univariate/Session${1}/

#set group level dir
set group_dir = $topdir/ImagingData/Level2GLM/Activation_Univariate/Session${1}/2sampleT/

#set output name
set today = `date +%m-%d-%y`

#set map_folder
set map_folder = `ls -d $group_dir/${motst}_*-*-*`

#set mask_file
set mask_file = `ls $model_dir/Session${1}_mask0.8_*HEAD`

###################### clusterize  ########################

#loop though all conditions/contrasts of interest
set groups = ( WholeGroup HighRisk LowRisk )
 
foreach g ( $groups )

    if ( "$g" == "WholeGroup" ) then
        set fileG = "WG"
    else if ( "$g" == "HighRisk" ) then
	set fileG = "HR"
    else if ( "$g" == "LowRisk" ) then
	set fileG = "LR"	    
    endif

    ###################### High_v_Low_PScon ######################
    set output_name = "High_v_Low_PScon"

    if ( -f "${map_folder}/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}+tlrc.HEAD" ) then
	
	#want to overwite?
	if ( "${overwrite}" == "Y" ) then
	    
    	#remove files
	    rm $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}*
	    rm $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k}*	
	    rm $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}*
			   
	    #re-clusterize
	    3dClusterize                  \
		-inset $map_folder/${fileG}_2sampleT++_${output_name}_${motst}+tlrc.      \
		-ithr 1                    \
		-idat 0                    \
		-mask $mask_file	   \
		-NN 2                      \
		-bisided p=$pvalue         \
		-clust_nvox $k             \
		-orient LPI                \
		-pref_map $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}          \
		-pref_dat $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k} > $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}
	endif
    else
	3dClusterize                  \
	    -inset $map_folder/${fileG}_2sampleT++_${output_name}_${motst}+tlrc.      \
	    -ithr 1                    \
	    -idat 0                    \
	    -mask $mask_file           \
	    -NN 2                      \
	    -bisided p=$pvalue         \
	    -clust_nvox $k             \
	    -orient LPI		       \
	    -pref_map $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}          \
	    -pref_dat $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k} > $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}
    endif

    ###################### Large_v_Small_EDcon ######################
    set output_name = "Large_v_Small_EDcon"
    
    if ( -f "${map_folder}/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}+tlrc.HEAD" ) then

        #want to overwite?
        if ( "${overwrite}" == "Y" ) then
            #remove files
            rm $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}*
            rm $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k}*
            rm $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}*

            #re-clusterize
            3dClusterize                  \
                -inset $map_folder/${fileG}_2sampleT++_${output_name}_${motst}+tlrc.      \
                -ithr 1                    \
                -idat 0                    \
                -mask $mask_file           \
                -NN 2                      \
                -bisided p=$pvalue         \
                -clust_nvox $k             \
		-orient LPI                \
                -pref_map $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}          \
                -pref_dat $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k} > $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}
        endif
    else
        3dClusterize                  \
            -inset $map_folder/${fileG}_2sampleT++_${output_name}_${motst}+tlrc.      \
            -ithr 1                    \
            -idat 0                    \
            -mask $mask_file           \
            -NN 2                      \
            -bisided p=$pvalue         \
            -clust_nvox $k             \
            -orient LPI                \
	    -pref_map $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}          \
            -pref_dat $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k} > $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}
    endif
end

###################### High Risk v Low Risk  ######################
set models = ( HighLarge HighSmall LowLarge LowSmall HighLarge-Small LowLarge-Small LargeHigh-Low SmallHigh-Low Large-Small_allED High-Low_allPS )

foreach m ( $models )
    set output_name = "$m"
    set fileG = "HR_v_LR"

    if ( -f "${map_folder}/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}+tlrc.HEAD" ) then

        #want to overwite?
        if ( "${overwrite}" == "Y" ) then
            #remove files
             rm $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}*
             rm $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k}*
             rm $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}*

             #re-clusterize
             3dClusterize                  \
                -inset $map_folder/${fileG}_2sampleT++_${output_name}_${motst}+tlrc.      \
                -ithr 1                    \
                -idat 0                    \
                -mask $mask_file           \
                -NN 2                      \
                -bisided p=$pvalue         \
                -clust_nvox $k             \
		-orient LPI                \
                -pref_map $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}          \
                -pref_dat $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k} > $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}
        endif
    else
        3dClusterize                  \
            -inset $map_folder/${fileG}_2sampleT++_${output_name}_${motst}+tlrc.      \
            -ithr 1                    \
            -idat 0                    \
            -mask $mask_file           \
            -NN 2                      \
            -bisided p=$pvalue         \
            -clust_nvox $k             \
            -orient LPI                \
	    -pref_map $map_folder/${fileG}_2sampleTClusMap_${output_name}_${motst}_p${pvalue}_k${k}          \
            -pref_dat $map_folder/${fileG}_2sampleTClusThresh_${output_name}_${motst}_p${pvalue}_k${k} > $map_folder/${fileG}_2sampleTClusReport_${output_name}_${motst}_p${pvalue}_k${k}
     endif
end
