#!/bin/tcsh
#
#Usage: extract_G2_pairedT
#  	                    
#
#The purpose of this script is to extract betas from clusters showing significant responses in paired-test (excuted via G2_pairedT)


###################### set up initial variables  ###########################
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO

#don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

#go to and set BIDS main directory
cd ../../../
set bidsdir = "$cwd"

#set test directory
set pairedt_test_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level2/2sample-pairedT/

# set group-level result directory
set res_dir = $pairedt_test_dir/ped_fd-0.9_b20_3runs_noGSR_03-24-23

# set level1 directory
set lev1_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level1

###################### Make cluster masks  ###########################
cd $res_dir

# Make masks of results that survive cluster thresholding 
# p-adjusted <.05
3dClusterize -nosum -1Dformat -inset $res_dir/WG_2sampleT++_Food_v_Office_PScon_medimp+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1544 -bisided -3.2905 3.2905 -pref_map clust_mask_pairedT_cuetype_PScon


###################### extract betas from combined mask ###########################

set contrasts = ( Large-Small_allED OfficeLarge-Small) 

foreach contrast ( $contrasts )

   set outfile = "betas_clust_mask_pairedT_cuetype_${contrast}.txt"

   if ( -f $res_dir/$outfile ) then
      rm $res_dir/$outfile
   endif

	# for each sub, extract average beta from mask and write to .txt file
	foreach sub ( `cat $res_dir/index_all_fd-0.9_b20_3runs.txt ` )
		# extract from combined mask
		3dROIstats -mask $res_dir/clust_mask_pairedT_cuetype_PScon+tlrc. $lev1_dir/sub-$sub/ped_fd-0.9_b20_noGSR/stats.sub-$sub+tlrc"[${contrast}_GLT#0_Coef]" >> ${res_dir}/${outfile}
	end
end