#!/bin/tcsh
#
#Usage: extract_G1_1sampleT
#  	                    
#
#The purpose of this script is to extract betas from clusters showing significant responses in 1-sample t-tests (executed via G1_1sampleT)


###################### set up initial variables  ###########################
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO

#don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

#go to and set BIDS main directory
cd ../../../
set bidsdir = "$cwd"

#set test directory
set t_test_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level2/1sampleT/

# set group-level result directory
set res_dir = $t_test_dir/ped_fd-0.9_b20_3runs_noGSR_03-21-23

# set level1 directory
set lev1_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level1

###################### Make cluster masks  ###########################
cd $res_dir

# Make masks of results that survive cluster thresholding 
# p-adjusted <.05
3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_Food-Office_GLT_medimp+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1475 -bisided -3.2905 3.2905 -pref_map clust_mask_1samp_Food-Office
3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_High-Low_allPS_GLT_medimp+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1519 -bisided -3.2905 3.2905 -pref_map clust_mask_1samp_High-Low_allPS
3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_Large-Small_allED_GLT_medimp+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1498 -bisided -3.2905 3.2905 -pref_map clust_mask_1samp_Large-Small_allED

3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_OfficeLarge-Small_GLT_medimp+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1521 -bisided -3.2905 3.2905 -pref_map clust_mask_1samp_OfficeLarge-Small

###################### extract betas from combined mask ###########################

set contrasts = ( Food-Office High-Low_allPS Large-Small_allED OfficeLarge-Small) 


foreach contrast ( $contrasts )

   set outfile = "betas_clust_mask_1samp_${contrast}.txt"

   if ( -f $res_dir/$outfile ) then
      rm $res_dir/$outfile
   endif

	# for each sub, extract average beta from mask and write to .txt file
	foreach sub ( `cat $res_dir/index_all_fd-0.9_b20_3runs.txt ` )
		# extract from combined mask
		3dROIstats -mask $res_dir/clust_mask_1samp_${contrast}+tlrc. $lev1_dir/sub-$sub/ped_fd-0.9_b20_noGSR/stats.sub-$sub+tlrc"[${contrast}_GLT#0_Coef]" >> ${res_dir}/${outfile}
	end
end