#!/bin/tcsh
#
#Usage: Gopt_MaskConjunction   $1
#                           results directory (e.g., ped_fd-0.9_b20_3runs_noGSR_01-22-23) 
#  	                    
#
#The purpose of this script is to get a conjunction map of 
#regions with PS responses for High ED, Low ED, and office images
#Adapted from scripts by Alaina Peace by Bari Fuchs Fall 2023.
#
###################### set up initial variables  ###########################
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO

#don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

#go to and set BIDS main directory
cd ../../../
set bidsdir = "$cwd"

#set test directory
set test_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level2/1sampleT/

# set result directory
set res_dir = $test_dir/$1


###################### Make cluster masks  ###########################
cd $res_dir

# Make masks of results that survive cluster thresholding 
# mask names: Clust_mask-PScon_hED, Clust_mask-PScon_lED, Clust_mask-PScon_office
3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_HighLarge-Small_GLT+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1000 -bisided -3.2905 3.2905 -pref_map Clust_mask-PScon_hED
3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_LowLarge-Small_GLT+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1000 -bisided -3.2905 3.2905 -pref_map Clust_mask-PScon_lED
3dClusterize -nosum -1Dformat -inset $res_dir/WG_1sampleT++_OfficeLarge-Small_GLT+tlrc.HEAD -idat 1 -ithr 1 -NN 2 -clust_nvox 1000 -bisided -3.2905 3.2905 -pref_map Clust_mask-PScon_office

###################### Make conjunction masks  ###########################

#1- hED only
#2- lED only
#3- hED + lED (food only)
#4- office only
#5- hED and office
#6- lED and office 
#7- hED, lED, and office 

3dcalc -a Clust_mask-PScon_hED+tlrc -b Clust_mask-PScon_lED+tlrc  \
   -c Clust_mask-PScon_office+tlrc  \
   -expr 'step(a)+2*step(b)+4*step(c)' -prefix PScon_conjunctionMask

gunzip PScon_conjunctionMask.gz
3dAFNItoNIFTI PScon_conjunctionMask+tlrc


