#!/bin/tcsh
#
#useage: G5b_

# The purpose of this script is to extrat beta values for a previously defined cluster
# Written by Bari Fuchs Fall 2022
###################### set up initial variables  ###########################   
#don't log AFNI programs in ~/.afni.log
setenv AFNI_DONT_LOGFILE YES
 
#dont try version checks
setenv ANFI_VRSION_CHECK NO
 
##don't auto-compress output files
setenv AFNI_COMPRESSOR NONE

###################### setup and check directories  ###########################   
cd ../../../
set bidsdir = "$cwd"

#set lev1 dir
set lev1_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level1

# set levl2 dir
set lev2_dir = $bidsdir/derivatives/analyses/foodcue-paper1/level2

#set test directory
set test_dir = $bidsdir/derivatives/analyses/FoodCue-fmri/Level2GLM/Activation_Univariate/ses-1/MVM

#set map directory
set map_dir = $test_dir/ped_fd-0.9_b20_3runs_09-19-22_2

if ( ! -d $map_dir ) then
	echo "failed to find $map_dir"
	exit
endif

# delete beta text file 
if ( -f $map_dir/inftemp_betas.txt ) then
	rm $map_dir/inftemp_betas.txt
endif

# add headers to new file
echo sub ' \t ' largePSedcon_beta ' \t ' smallPSedcon >> $map_dir/inftemp_betas.txt

# loop through subjects
foreach i ( `cat $index_dir/index_all_fd-0.9_b20_3runs.txt ` )
	set sub = $i
	set large_beta = `3dmaskave -mask $map_dir/inftemp_mask+tlrc. $lev1_dir/sub-$sub/ped_fd-0.9_b20/stats.sub-$sub+tlrc'[LargeHigh-Low_GLT#0_Coef]'`
	set small_beta = `3dmaskave -mask $map_dir/inftemp_mask+tlrc. $lev1_dir/sub-$sub/ped_fd-0.9_b20/stats.sub-$sub+tlrc'[SmallHigh-Low_GLT#0_Coef]'`
	echo $sub ' \t ' $large_beta ' \t ' $small_beta >> $map_dir/inftemp_betas.txt 
end


# make a maps of clusters that survive cluster thresholding
3dClusterize -nosum -1Dformat -inset $lev2_dir/1sampleT/ped_fd-0.9_b20_3runs_noGSR_12-07-22_noclustsim/WG_1sampleT++_High-Large_allPS_GLT_bodyfat+tlrc.HEAD -idat 9 -ithr 9 -NN 2 -clust_nvox 40 -bisided -3.2905 3.2905 -pref_map Clust_mask-EDcon_bodyfat
