#!/bin/bash
#
#useage: G0_copylevel1  $1
# 					Participant

# The purpose of this script is to copy level 1 analyses in paper-specific analysis folder


###################### set up initial variables  ###########################

#set input argument 1 to variable 'subID' and make sure it has leading zeros

#remove leading zeros if they were included -- trying to add leading zeros to numbers with leading zeros can lead to issues (https://stackoverflow.com/questions/8078167/printf-in-bash-09-and-08-are-invalid-numbers-07-and-06-are-fine)
ID_nozero=$(echo $1 | sed 's/^0*//')

# add leading zeros back
ID=`printf %03d $ID_nozero`
subID="sub-$ID"


###################### setup and check directories  ###########################   
#go to and set BIDS main directory
cd ../../../
bidsdir=$(pwd)

# set subject fmriprep functional dir
fmriprep_subdir="$bidsdir/derivatives/preprocessed/fmriprep/$subID/ses-1/func"

# set shared level 1 dir
lev1_shared="$bidsdir/derivatives/afni-level1"

#set project level1 dir
lev1_dir="$bidsdir/derivatives/analyses/foodcue-paper3/level1"


###################### copy folders  ########################

# make directory 
if [ ! -d "$lev1_dir/$subID/" ]; then
 		mkdir -p $lev1_dir/$subID/
fi

# copy mask
if [ ! -f $lev1_dir/$subID/foodcue_full_mask-MNIPediatricAsym_cohort-3_res-1.nii ]; then
	cp $fmriprep_subdir/foodcue_full_mask-MNIPediatricAsym_cohort-3_res-1.nii $lev1_dir/$subID/
fi

# # for each level 1 folder
# for folder in f31_GSR f31
# do

# 	echo "$subID/$folder"

# 	# make folder directory 
# 	if [ ! -d "$lev1_dir/$subID/$folder" ]; then
# 		mkdir -p $lev1_dir/$subID/$folder
# 	fi
		
# 	# copy .BRIK
# 	if [ ! -f "$lev1_dir/$subID/$folder/stats.$ID+tlrc.BRIK" ]; then
# 		cp $lev1_shared/$subID/$folder/stats.$ID+tlrc.BRIK $lev1_dir/$subID/$folder
# 	fi

# 	# copy .HEAD
# 	if [ ! -f "$lev1_dir/$subID/$folder/stats.$ID+tlrc.HEAD" ]; then
# 		cp $lev1_shared/$subID/$folder/stats.$ID+tlrc.HEAD $lev1_dir/$subID/$folder
# 	fi

# done
