#!/bin/bash

# The purpose of this script is to run smoothing and scaling of bold image, create a mask,
# generate onset files, censor files, and regression files, and run first-level analyses
#and organize them for participant R01_PARNUM

#This script was generated on DATE

######## Set up AFNI Environmental Variables ########
#don't log AFNI programs in ~/.afni.log
AFNI_DONT_LOGFILE="YES"

#dont try version checks
ANFI_VRSION_CHECK="NO"

##don't auto-compress insert files
AFNI_COMPRESSOR="NONE"

#set number of processors for AFNI. 10 is the number of cores that will be used to run the job
OMP_NUM_THREADS="10"

######## Set up Script Variables ########
#date
today=`date +%m-%d-%y`

#set top/base directory
topdir="/gpfs/group/klk37/default/R01_Food_Brain_Study/BIDS"

#insert start of this section
echo "## Started: `date`"



######## 1: Scaling and Smoothing of preprocessed functional data  (1_smooth-scale) ########
#insert header for this subsection in output
echo "######## Smoothing and scaling (1_smooth-scale) ########"
echo ""

#be sure script is starting Script directory
cd $topdir/code/afni/mod_scripts

#run 1_smooth-scale script
bash 1_smooth-scale PARNUM SESNUM



######## 2: Create 1 mask by combining separate run masks (2_createmask) ########
#insert header for this subsection in output
echo "######## Creating subject mask (2_createmask) ########"
echo ""

#be sure script is starting Script directory
cd $topdir/code/afni/mod_scripts

#run 2_createmask script
bash 2_createmask PARNUM SESNUM 



######## 3: Generate original onset files (3_getonsets) ########
#insert header for this subsection in output
echo "######## Generating original onset files (3_getonsets) ########"
echo ""

#be sure script is starting Script directory
cd $topdir/code/afni/mod_scripts

#run 3_getonsets.py script
#python 3_getonsets.py -p PARNUM
echo "for SSIB abstract analyses: 4_create_censor_files.py was run locally on Bari's computer, and orig onset files were rsynced to Roar"


######## 4: Create censor/regressor files and modified timing files (4_create_censor_files) ########
#insert header for this subsection in output
echo "######## Creating censor/regressor files and modified timing files (4_create_censor_files) ########"
echo ""

#be sure script is starting Script directory
cd $topdir/code/afni/mod_scripts

#run 4_create_censor_files.py script
#python 4_create_censor_files.py -p PARNUM -fd 1.0 -svd 1.8 -r 20   
echo "for SSIB abstract analyses: 4_create_censor_files.py was run locally on Bari's computer, and censor and regressor files were rsynced to Roar"


######## 5: Run first-level analyses (4_3ddeconvolve) ########

#insert header for this subsection in output
echo "######## First-level analyses (5_3ddeconvolve) ########"
echo ""

#be sure script is starting Script directory
cd $topdir/code/afni/mod_scripts

#run 5_3ddeconvolve script
bash 5_3ddeconvolve PARNUM SESNUM Ped fd-1.0_stddvar-1.8 20






#insert ending time for this section
echo "## Part2 Ended: `date`"
