#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pytest
import pandas as pd
import numpy as np

# pytest fixtures are functions that can create data, test doubles, or initialize system state for the test suite. 
# Any test that wants to use a fixture must explicitly use this fixture function as an argument to the test 
# function, so dependencies are always stated up front.

#@pytest.fixture
#def confound_files_fixture():

#@pytest.fixture
#def regress_pardat_fixture():

@pytest.fixture
def confound_dat_fixture():

    confound_dat = pd.DataFrame(np.zeros((80, 3)))
    confound_dat.columns = ['framewise_displacement','std_dvars', 'non_steady_state_outlier00']
    confound_dat.at[np.r_[:20, 40:46],["framewise_displacement"]] = 1.1 # set rows 0:20 & 40:46 to have framewise displacement of 1.1
    confound_dat.at[50:55,["std_dvars"]] = 1.1                          # set rows 50:55 to have std_dvars of 1.1
    confound_dat.at[75:79,["non_steady_state_outlier00"]] = 1           # set rows 75:79 to have framewise displacement of 1.1

    return confound_dat


@pytest.fixture
def r_int_list_fixture():

    # Make list of 1s and 0s, where 1 indicates TR of interest, 0 indicates TR of no interest
    r_int_list = [0] * 80 # make list of zeros
    r_int_list[2:11] = [1, 1, 1, 1, 1, 1, 1, 1, 1]    #At indices 2:11 in r_int_list, set value to 1
    r_int_list[15:24] = [1, 1, 1, 1, 1, 1, 1, 1, 1]   #At indices 15:24 in r_int_list, set value to 1
    r_int_list[28:37] = [1, 1, 1, 1, 1, 1, 1, 1, 1]   #At indices 28:37 in r_int_list, set value to 1
    r_int_list[41:50] = [1, 1, 1, 1, 1, 1, 1, 1, 1]   #At indices 41:50 in r_int_list, set value to 1
    r_int_list[54:63] = [1, 1, 1, 1, 1, 1, 1, 1, 1]   #At indices 54:63 in r_int_list, set value to 1
    r_int_list[67:76] = [1, 1, 1, 1, 1, 1, 1, 1, 1]   #At indices 67:76 in r_int_list, set value to 1

    return r_int_list

@pytest.fixture
def censor_info_fixture():

    # Make lists of 1s and 0s, where 1 indicates uncensored TR, 0 indicates censored TR. 
    # Lists will be based on dataframe generated by confound_dat_fixture()
    # Note: first 2 TRs should always be censored, non_steady_state_outlier00 = 1 should always be censored

    # if censoring for framewise displacement > 1
    fd_1 = [1] * 80
    index_list = list(range(0,20)) + list(range(40,46)) + list(range(75,79))
    for i in range(len(fd_1)):
            if i in index_list:
                fd_1[i] = 0

    # if censoring for framewise displacement > 1 and stddvar > 1
    fd1_stddvar1 = [1] * 80

    # if censoring for framewise displacement > 1, and censoring previous TR if framewise displacement > 1
    fd1_cpt = [1] * 80

    # put lists into a dictionary
    censor_info_dict = {} # make empty dictionary
    censor_info_dict["fd-1.0"] = fd_1
    censor_info_dict["fd-1.0_stddvar-1.0"] = fd1_stddvar1
    censor_info_dict["fd-1.0_cpt"] = fd1_cpt

    return censor_info_dict

    