#!/bin/bash
#usage: ./1_smoothing     $1          $2    
#		    ParicipantID   Session
#		    
#
### This script will smooth and scale fmriprep func output for each individua ###
### AFNI code was derived from https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/fMRIPrep_Demo_4_AdditionalPreproc.html
 


###################### set up initial variables  ###########################

#set input argument 1 to variable 'subID' and make sure it has leading zeros

#remove leading zeros if they were included -- trying to add leading zeros to numbers with leading zeros can lead to issues (https://stackoverflow.com/questions/8078167/printf-in-bash-09-and-08-are-invalid-numbers-07-and-06-are-fine)
ID_nozero=$(echo $1 | sed 's/^0*//')

# add leading zeros back
ID=`printf %03d $ID_nozero`
subID="sub-$ID"
session="Session$2"

###################### setup and check directories  ###########################
#go to and set BIDs as main directory
cd ../../../
topdir=$(pwd)
 
#set parDir to participants fmriprep func directory
parDir="$topdir/derivatives/preprocessed/fmriprep/$subID/ses-$2/func"
 
#check for participant fmriprep directory, exit if doesnt exist
if [ -d "$parDir" ]
then
     echo "Starting afni preprocessing for $subID in $session"
else
     echo "fmriprep/ses-$2/func directory does not exist for participant $subID"
     exit
fi

###################### AFNI: smoothing and scaling  ###########################
cd $parDir

# get list of runs and templates
#runs=`find *run*desc-preproc_bold.nii.gz -type f -exec basename "{}" \; | grep -o -P '(?<=foodcue_run-).*(?=_space)'| sort -u`
#templates=`find *run*desc-preproc_bold.nii.gz -type f -exec basename "{}" \; | grep -o -P '(?<=space-).*(?=_desc)'| sort -u`

# get list of foodcue preproc_bold filenames without .nii.gz extension
#files=`find *foodcue*desc-preproc_bold.nii.gz -type f -exec basename "{}" \; | cut -f1 -d"."`

# get list of preprocessed files and extract basenames with everything from sub-XXX...to _desc 
files=`find *run*desc-preproc*.nii.gz -type f -exec basename "{}" \; | sed 's/-[^-]*$//' | sort -u`

# set blur size
blursize="6"

# smooth and scale each file
for basename in $files; do

	if [ -f "${basename}-blur${blursize}.nii" ]
	then
		echo "${basename}-blur${blursize}.nii exists. skipping smoothing"
	else
		# apply smoothing to *preproc_bold.nii.gz
		3dmerge -1blur_fwhm $blursize -doall -prefix ${basename}-blur${blursize}.nii \
		${basename}-preproc_bold.nii.gz
	fi

	if [ -f "${basename}-blur${blursize}-scale.nii" ] 
	then
		echo "${basename}-blur${blursize}-scale.nii exists. skipping scaling"
	else
		# apply scaling to blur*.nii to ensure that the mean BOLD signal across the run is 100
		3dTstat -prefix rm.mean_${basename}.nii ${basename}-blur${blursize}.nii
		3dcalc -a ${basename}-blur${blursize}.nii -b rm.mean_${basename}.nii \
			-c ${basename}-brain_mask.nii.gz \
			-expr 'c * min(200, a/b*100)*step(a)*step(b)' \
			-prefix ${basename}-blur${blursize}-scale.nii
	fi
done

rm rm*
