#!/bin/bash
#usage: ./4_3dDeconvolve     $1          $2   	 $3		$4  						$5
#		    	ParticipantID   Session Template   TR-Censor-criteria (e.g., fd-1.0)	Run or block censor criteria (e.g.,b20)
#		    
#
### This script will run 3ddeconvolve ###
### AFNI code was derived from https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/fMRIPrep_Demo_4_AdditionalPreproc.html
 


###################### set up initial variables  ###########################

#set input argument 1 to variable 'subID' and make sure it has leading zeros

#remove leading zeros if they were included -- trying to add leading zeros to numbers with leading zeros can lead to issues (https://stackoverflow.com/questions/8078167/printf-in-bash-09-and-08-are-invalid-numbers-07-and-06-are-fine)
ID_nozero=$(echo $1 | sed 's/^0*//')

# add leading zeros back
ID=`printf %03d $ID_nozero`
subID="sub-$ID"
session="Session$2"

# set censor criteria variables
TRcen="$4"
runcen="$5"

# set template string
if [ "$3" == "Ped" ]
then
	temp="MNIPediatricAsym_cohort-3"
	tempst="ped"
	echo "template for 3ddeconvolve is $temp"
elif [ "$3" == "MNI" ]
then
	temp="MNI152NLin2009cAsym"
	tempst="MNI"
	echo "template for 3ddeconvolve is $temp"
else
	echo "please specify template as Ped or MNI. Exiting 4_3dDeconvlve"
fi



###################### setup and check directories  ###########################
# assign output directory name

#go to and set BIDs as main directory
cd ../../../
topdir=$(pwd)

#set onset file directory
onsetDir="$topdir/derivatives/preprocessed/foodcue_onsetfiles/${TRcen}_${runcen}"

#set parDir to participants fmriprep ses directory
parDir="$topdir/derivatives/preprocessed/fmriprep/$subID/ses-$2"

#set output directory
output_dir="$topdir/derivatives/afni-level1/${subID}/${tempst}_${TRcen}_${runcen}_noGSR"
 
# verify that the results directory with output does not yet exist
if [ -d $output_dir ]
then
	if [ "$(ls -A $output_dir)" ]
	then
		echo "output dir already exists and is not empty. Exiting 4_3dDeconvolve"
 		exit
	else
		echo "output dir exists but is empty. Deleting output dir"
		rm -r $output_dir
	fi
fi

#check for participant fmriprep directory, exit if doesnt exist
if [ ! -d $parDir ]
then
	echo "fmriprep/ses-$2/ directory does not exist for participant $subID. Exiting 4_3dDeconvolve"
	exit
fi

# verify that stimtime files exist
cd $onsetDir
stimfiles=(` ls ${subID}*.txt`)

if [ "${#stimfiles[@]}" = 6 ]
then    
        echo "starting 3ddeconvolve for ${subID} ${session}" 
else
        echo "${TRcen}_p${runcen} onset files are missing for $subID. Exiting 4_3dDeconvolve"
        exit
fi


# create results and stimuli directories
mkdir -p $output_dir


###################### AFNI: 3dDeconvolve  ###########################
# run the first-level regression analysis
cd $output_dir

# note: stim_times_subtract is set equal to TR/2 to adjust for how fmriprep does slice time correction
# see https://reproducibility.stanford.edu/slice-timing-correction-in-fmriprep-and-linear-modeling/

3dDeconvolve -input $parDir/func/*foodcue*${temp}*blur6-scale.nii                            				\
   	-censor $parDir/func/${subID}_foodcue-allruns_censor_${TRcen}.tsv            			\
	-mask $parDir/func/foodcue_full_mask*${temp}*.nii					\
    	-polort 2                                                               		\
	-num_stimts 20                                                                          \
	-stim_times_subtract 1									\
	-stim_times 1 $onsetDir/${subID}_HighLarge*.txt 'BLOCK(18,1)'	\
	-stim_label 1 HighLarge                  						\
	-stim_times 2 $onsetDir/${subID}_HighSmall*.txt 'BLOCK(18,1)'    \
	-stim_label 2 HighSmall     								\
	-stim_times 3 $onsetDir/${subID}_LowLarge*.txt 'BLOCK(18,1)' 	\
	-stim_label 3 LowLarge     								\
	-stim_times 4 $onsetDir/${subID}_LowSmall*.txt 'BLOCK(18,1)'     \
	-stim_label 4 LowSmall     								\
	-stim_times 5 $onsetDir/${subID}_OfficeLarge*.txt 'BLOCK(18,1)'  \
	-stim_label 5 OfficeLarge     								\
	-stim_times 6 $onsetDir/${subID}_OfficeSmall*.txt 'BLOCK(18,1)'  \
	-stim_label 6 OfficeSmall     								\
	-stim_file 7 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[0]' -stim_base 7 -stim_label 7 trans_x_01    		\
	-stim_file 8 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[1]' -stim_base 8 -stim_label 8 trans_y_01   		\
	-stim_file 9 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[2]' -stim_base 9 -stim_label 9 trans_z_01     	\
	-stim_file 10 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[3]' -stim_base 10 -stim_label 10 rot_x_01  		\
	-stim_file 11 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[4]' -stim_base 11 -stim_label 11 rot_y_01   		\
	-stim_file 12 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[5]' -stim_base 12 -stim_label 12 rot_z_01   		\
    -stim_file 13 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[6]' -stim_base 13 -stim_label 13 csf             \
    -stim_file 14 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[7]' -stim_base 14 -stim_label 14 white_matter             \
    -stim_file 15 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[9]' -stim_base 15 -stim_label 15 trans_x_02        \
    -stim_file 16 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[10]' -stim_base 16 -stim_label 16 trans_y_02                \
    -stim_file 17 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[11]' -stim_base 17 -stim_label 17 trans_z_02        \
    -stim_file 18 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[12]' -stim_base 18 -stim_label 18 rot_x_02          \
    -stim_file 19 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[13]' -stim_base 19 -stim_label 19 rot_y_02         \
    -stim_file 20 $parDir/func/${subID}_foodcue-allruns_confounds-header.tsv'[14]' -stim_base 20 -stim_label 20 rot_z_02         \
	-gltsym 'SYM: HighLarge -HighSmall' -glt_label 1 HighLarge-Small                        \
	-gltsym 'SYM: LowLarge -LowSmall' -glt_label 2 LowLarge-Small                           \
    -gltsym 'SYM: HighLarge -LowLarge' -glt_label 3 LargeHigh-Low                           \
    -gltsym 'SYM: HighSmall -LowSmall' -glt_label 4 SmallHigh-Low                           \
    -gltsym 'SYM: HighLarge LowLarge -HighSmall -LowSmall' -glt_label 5 Large-Small_allED   \
    -gltsym 'SYM: HighLarge HighSmall -LowLarge -LowSmall' -glt_label 6 High-Low_allPS      \
    -gltsym 'SYM: .5*HighLarge .5*HighSmall .5*LowLarge .5*LowSmall -OfficeLarge -OfficeSmall' -glt_label 7 Food-Office 	\
	-gltsym 'SYM: OfficeLarge -OfficeSmall' -glt_label 8 OfficeLarge-Small 	\
    -jobs 8                                                    				\
    -fout -tout -x1D X.xmat.1D -xjpeg X.jpg -xsave                             		\
    -x1D_uncensored X.nocensor.xmat.1D                                       		\
    -fitts fitts.$subID                                                       		\
    -errts errts.$subID                                                     		\
    -bucket stats.$subID

# execute the 3dREMLfit script, written by 3Ddeconvolve
tcsh -x stats.REML_cmd

# copy mask into level-1 analyses folder
cp $parDir/func/foodcue_full_mask*${temp}*.nii $output_dir
