#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script was created to generate onset files that include blocks with good motion and exclude blocks with bad motion
This script will reference task-foodcue_bycond-censorsummary_fd-XX.tsv, generated by 4c_byblock-motion-summary.py

Written by Bari Fuchs in Summer 2022

Copyright (C) 20120 Bari Fuchs

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program.  If not, see <https://www.gnu.org/licenses/>.
     
This script is not guaranteed to work for new data or under new directory 
configurations, however, it should work if no changes are made to directories
or raw data configurations.

@author: baf44
"""

#set up packages    
from email import header
from pickle import TRUE
from aem import con
import numpy as np
import pandas as pd
import os
from pathlib import Path

##############################################################################
####                                                                      ####
####                             Core Script                              ####
####                                                                      ####
##############################################################################

# get script location
script_path = Path(__file__).parent.resolve()

# change directory to base directory (BIDSdat) and get path
os.chdir(script_path)
os.chdir('../../..')
base_directory = Path(os.getcwd())

#set specific paths
bids_onset_path = Path(base_directory).joinpath('derivatives/preprocessed/foodcue_onsetfiles')
bids_origonset_path = Path(base_directory).joinpath('derivatives/preprocessed/foodcue_onsetfiles/orig')
bids_fmriprep_path = Path(base_directory).joinpath('derivatives/preprocessed/fmriprep')

## CHANGE THIS TO BE AN INPUT OPTION TO SPECIFY 1 FILE
# import bycond-censor summary file specified in input
#censorsum_file = list(Path(bids_fmriprep_path).rglob('task-foodcue_bycond-censorsummary*'))

# set minimum number of TRs per block
min_blockTR = 7

## For subject
    ## Get original onset files

    ## For onset file
    
        # get onset file condition

        ## For row, r,  in onset file

            ## find cell in task-foodcue_bycond-censorsummary_fd-XX.tsv that correponds to onset file condition and row r

            ## if value in cell is < min_blockTR 

                # Change value in onset file column 0, row r to *
